import React, { useState , useEffect, useCallback} from 'react';
import './Slideshow.css'; // Optional: Create a separate CSS file for styles

// Slide Component
const Slide = ({ character, line, bgColor = 'bg-black', textColor = 'text-white' }) => (
  <div className={`flex items-center justify-center w-full h-screen ${bgColor} ${textColor} p-8`}>
    <div className="text-center max-w-4xl">
      <h1 className="text-4xl font-bold mb-4">{character}</h1>
      <p className="text-2xl italic">"{line}"</p>
    </div>
  </div>
);

// Slideshow Component
const Slideshow = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const slides = [
    { character: "", line: "Sunrise" },
    { character: "CHEN BAILU", line: "Come on in! I say, why don't you come in? Come in. What are you afraid of?" },
    { character: "FANG DASHENG", line: "Nothing! There is nobody here, right?" },
    { character: "CHEN BAILU", line: "Who knows? Probably not." },
    { character: "FANG DASHENG", line: "Disgusting. Can't get away from people in this place." },
    { character: "CHEN BAILU", line: "So what if there were anyone here? You can't be shy of people when you live here." },
    { character: "FANG DASHENG", line: "So this is where you've been living all these years." },
    { character: "CHEN BAILU", line: "What? Is there anything wrong with it?" },
    { character: "FANG DASHENG", line: "Um---no, it's fine!" },
    { character: "CHEN BAILU", line: "Why don't you take your clothes off?" },
    { character: "FANG DASHENG", line: "Oh, um, my clothes? Oh, no, I haven't, haven't taken them off." },
    { character: "CHEN BAILU", line: "I know you haven't. I mean, why are you so polite that you won't even take your coat off without being asked?" },
    { character: "FANG DASHENG", line: "Um---Perhaps, it's because I'm not used to taking my coat off right after going inside... Is it a bit cold inside?" },
    { character: "CHEN BAILU", line: "Cold? It's very hot to me." },
    { character: "FANG DASHENG", line: "Perhaps the window isn't closed?" },
    { character: "CHEN BAILU", line: "No, it can't be. Look, it's shut tight. Look! Come and look!" },
    { character: "FANG DASHENG", line: "What?" },
    { character: "CHEN BAILU", line: "Look! Frost! There's frost!" },
    { character: "FANG DASHENG", line: "So it was frost! You're so..." },
    { character: "CHEN BAILU", line: "It's odd, having frost when it's already spring." },
    { character: "FANG DASHENG", line: "Yes, very odd." },
    { character: "CHEN BAILU", line: "I love frost! Remember how I loved it when I was a kid? It's so beautiful and lovely! Look, look at that, isn't that me?" },
    { character: "FANG DASHENG", line: "What?" },
    { character: "CHEN BAILU", line: "The frost on the window, this bit. No, this bit. Look, isn't that my eyes? This sticking out is a nose, and where it goes in there is a mouth, and this bit is my hair. Look at this, it's exactly me!" },
    { character: "FANG DASHENG", line: "Ur...I can't see that." },
    { character: "CHEN BAILU", line: "What? It's like me, it's like me! I said it's like me!" },
    { character: "FANG DASHENG", line: "Alright alright, it's like you." },
    { character: "CHEN BAILU", line: "So you also think it's like me. Hey! This bit is like you!" },
    { character: "FANG DASHENG", line: "Like me?" },
    { character: "CHEN BAILU", line: "Obviously." },
    { character: "FANG DASHENG", line: "Which part?" },
    { character: "CHEN BAILU", line: "Here! It's here!" },
    { character: "FANG DASHENG", line: "I, I still can't see that." },
    { character: "CHEN BAILU", line: "Oh, you're still as pigheaded as ever. You're impossible." },
    { character: "FANG DASHENG", line: "Am I? I've been watching you all night but just now was the first time you've been like you used to be." },
    { character: "CHEN BAILU", line: "What do you mean?" },
    { character: "FANG DASHENG", line: "You're still the little girl that you used to be." },
    { character: "CHEN BAILU", line: "You mean, before? Still the little girl that I used to be?" },
    { character: "FANG DASHENG", line: "Yes, what?" },
    { character: "CHEN BAILU", line: "Dasheng, was there really a time I was like that, a little girl?" },
    { character: "FANG DASHENG", line: "Only if you'd come with me, you could be as free as you ever were." },
    { character: "CHEN BAILU", line: "Humph, freedom?" },
    { character: "FANG DASHENG", line: "You-" },
    { character: "CHEN BAILU", line: "What are you looking at now?" },
    { character: "FANG DASHENG", line: "Nothing... This place you've got here, it's quite, quite nice." },
    { character: "CHEN BAILU", line: "Nice? Somewhere to live, that's all. Tired?" },
    { character: "FANG DASHENG", line: "No, I'm all right.-I sat all the time while you were dancing with those people." },
    { character: "CHEN BAILU", line: "Why didn't you dance?" },
    { character: "FANG DASHENG", line: "I don't dance, I've told you. Also I don't want to dance like I'm crazy." },
    { character: "CHEN BAILU", line: "Crazy? That's right! That's the sort of crazy life I have. There's a rooster crowing." },
    { character: "FANG DASHENG", line: "That's odd, hearing a rooster crow in a place like this." },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "There's a market nearby. Guess what time is it now." },
    { character: "FANG DASHENG", line: "Perhaps half past five. It's almost dawn. I was looking at my watch every five minutes at that dance floor." },
    { character: "CHEN BAILU", line: "Are you in that much of a hurry?" },
    { character: "FANG DASHENG", line: "You know I've been living in the country for a long time now; I get impatient in places like that." },
    { character: "CHEN BAILU", line: "How about now?" },
    { character: "FANG DASHENG", line: "I'm more at ease now, of course. I thought that you've got no one here, and I could have a word with you." },
    { character: "CHEN BAILU", line: "Yes, but it's almost morning. Why aren't you sitting down?" },
    { character: "FANG DASHENG", line: "You - you haven't sat down yet." },
    { character: "CHEN BAILU", line: "You're such a nerd. Friends who come to my place don't wait for me to let them sit down. Now sit down. I'm thirsty, so I hope you'll excuse me for a moment for a sip of water. Cigarette?" },
    { character: "FANG DASHENG", line: "I told you I don't smoke." },
    { character: "CHEN BAILU", line: "Poor you! You are a paragon of virtue." },
    { character: "FANG DASHENG", line: "I never expected, Zhujun, that you'd change-" },
    { character: "CHEN BAILU", line: "Wait a minute, what did you just call me?" },
    { character: "FANG DASHENG", line: "Your name, you don't like it or something?" },
    { character: "CHEN BAILU", line: "Zhujun, Zhujun, it seems years since anyone called me that. Dasheng, call me that again." },
    { character: "FANG DASHENG", line: "Zhujun." },
    { character: "CHEN BAILU", line: "How bittersweet. Call me that once again." },
    { character: "FANG DASHENG", line: "Oh Zhujun, you have no idea how I-- Is there really no one here?" },
    { character: "CHEN BAILU", line: "No, of course not." },
    { character: "FANG DASHENG", line: "When I see what you're like now, I- if only you know my heart--" },
    { character: "THE VISITOR", line: "Sh!" },
    { character: "CHEN BAILU", line: "Georgy!" },
    { character: "FANG DASHENG", line: "Sh! What did you say? What was that, your heart? Who is this, Bailu?" },
    { character: "FANG DASHENG", line: "Zhujun? Who is he? Who's this man?" },
    { character: "GEORGY", line: "Zhujun? You're mistaken. Her name is Bailu. She's the queen here, and she's my, uh, the one I admire the most---" },
    { character: "CHEN BAILU", line: "You're drunk!" },
    { character: "GEORGY", line: "Me? I'm not drunk! It's you who're drunk! And you! Just look at you, all drunk and confused, with your eyes staring. Pah! I can't stand it." },
    { character: "CHEN BAILU", line: "What are you doing here?" },
    { character: "FANG DASHENG", line: "Yeah, what are you doing here?" },
    { character: "GEORGY", line: "I---uh---I was tired, I want to go to sleep. But wait, you're both here, too!" },
    { character: "CHEN BAILU", line: "This is where I live, of course I'm here!" },
    { character: "GEORGY", line: "Where you live?" },
    { character: "CHEN BAILU", line: "And what were you doing in my bedroom?" },
    { character: "GEORGY", line: "What? I came out of your bedroom? No, I didn't... didn't. Let me just think..." },
    { character: "CHEN BAILU", line: "Think, he said!" },
    { character: "GEORGY", line: "Wait a minute. Wait. Don't rush me. Now let me work things out slowly. So I drank, and I turned, and after turning, I drank again, and I turned, and turned, and turned, and turned, and then "},
    { character: "GEORGY", line: "-- then? Oh, and then I got on the elevator, - oh, that's right, that's right, I entered this room... No, no, I went inside. And then I took off my clothes and flopped down on the bed. " },
    { character: "GEORGY", line: "And then I just lay there. And then I felt sick, and --ugh!-- That's right, that's what happened. Well, of course, I'm now out here!"},
    { character: "CHEN BAILU", line: "Georgy, you're out of your mind tonight!" },
    { character: "GEORGY", line: "Sh! Hear me out, rest assured, I'm not out of my mind. First I fell asleep on your bed, and then because I drank a little bit too much, I seemed to have-- Oh damn, I feel sick again. "},
    { character: "GEORGY", line: "Pardon me, mademoiselle, excuse me, miss! Oh sir, excuse me. Pardon, Monsieur. Goodbye. Good night! Good night! My lady and gentleman! Oh good-bye, au revoir, et monsieur, I---I---I Shall---I Shall ---"},
    { character: "FANG DASHENG", line: "Who was that?" },
    { character: "CHEN BAILU", line: "One of our choicer local products, don't you think he's quite fun?" },
    { character: "FANG DASHENG", line: "Fun? That was a maniac! I don't understand why you hang out with someone like this? Who is he? How did he grow so close to you?" },
    { character: "CHEN BAILU", line: "So you want to know? He is one of our choicer local products, a foreign student, he said he's a PH.D. or an M.A. or something. His English name is George. "},
    { character: "CHEN BAILU", line: "Abroad his name is George Zhang, here it's Zhang George. Since he's been back he's apparently had several administrative posts, and he's got a few bucks in his pocket." },
    { character: "FANG DASHENG", line: "But why do you know such a thing? Can't you see that it's a nasty piece of rubbish?" },
    { character: "CHEN BAILU", line: "Haven't I just told you? He's got money." },
    { character: "FANG DASHENG", line: "You mean, just because he's got money you..." },
    { character: "CHEN BAILU", line: "If he's got money of course he can get close to me. When I was at the dance-hall he was after me for a while." },
    { character: "FANG DASHENG", line: "No wonder he behaved like that to you." },
    { character: "CHEN BAILU", line: "You're a real countryman, you're so serious about everything. Wait till you've been here for some time and you'll know living is all about. Everyone's like that."},
    { character: "CHEN BAILU", line: "Don't be so pretentious. Now that there's no one here, let's get back to what you wanted to say earlier?" },

    // Add more slides as needed...
    { character: "FANG DASHENG", line: "What was I trying to say earlier?" },
    { character: "CHEN BAILU", line: "You have a poor memory. You were telling me about your heart, when this Mr. Zhang Georgy arrived." },
    { character: "FANG DASHENG", line: "Ah yes, my heart. I'm that kind of person who always lives by his heart. But Zhujun, when I see you like this, you can't imagine how my heart---Mr. Zhang again, I think." },
    { character: "WANG FUSHENG", line: "It's not Mr. Zhang, it's me. Miss Chen, you're back early" },
    { character: "CHEN BAILU", line: "Did you want to see me about something?" },
    { character: "WANG FUSHENG", line: "You saw Mr. Zhang just now." },
    { character: "CHEN BAILU", line: "Yes, so what?" },
    { character: "WANG FUSHENG", line: "I helped him to another room and put him to bed." },
    { character: "CHEN BAILU", line: "He can go wherever he wants to. You don't have to come and tell me about it." },
    { character: "WANG FUSHENG", line: "That's right. Mr. Zhang said he's terribly sorry for getting drunk and coming into your suite and puking on your bed, and--" },
    { character: "CHEN BAILU", line: "What! He puked on my bed?" },
    { character: "WANG FUSHENG", line: "Yes, but don't worry, Miss Chen. I'll clean it up for you right now. You don't want to go in there, either, it might be unpleasant." },
    { character: "CHEN BAILU", line: "The beast, he - alright, go ahead." },
    { character: "WANG FUSHENG", line: "Yes. You're not home all night, but you've had a lot of visitors. Mr. Li, Mr. Fang and Mr. Liu. Mr. Pan the bank-manager came three times to see you. " },
    { character: "WANG FUSHENG", line: "And then there was a call from Mrs. Gu saying could you go to her mansion tomorrow---er, today---to spend the evening with them."},
    { character: "CHEN BAILU", line: "I see. You can give here a call later on and ask her here this afternoon." },
    { character: "WANG FUSHENG", line: "And Mr. Hu said he'd be coming to visit you soon." },
    { character: "CHEN BAILU", line: "Tell him he can come if he wants to. Anyone's welcome here." },
    { character: "WANG FUSHENG", line: "Then there was the newspaper-editor, Mr. Zhang---" },
    { character: "CHEN BAILU", line: "Yes, yes, tell him to come over today if he's free." },
    { character: "WANG FUSHENG", line: "Oh yes, and Mr. Pan looked in three times at night, and now he's---" },
    { character: "CHEN BAILU", line: "I know, I know. You already told me that." },
    { character: "WANG FUSHENG", line: "But, Miss Chen, now that this gentleman here---" },
    { character: "CHEN BAILU", line: "Oh, he's a cousin of mine." },
    { character: "FANG DASHENG", line: "Cousin?" },
    { character: "CHEN BAILU", line: "He'll be sleeping here later." },
    { character: "FANG DASHENG", line: "No Zhujun, I'm not, I'll be going soon." },
    { character: "CHEN BAILU", line: "Very well then, please yourself. That's all, then. Now you can go and clean my bed." },
    { character: "FANG DASHENG", line: "Zhujun, how could you turn into this?" },
    { character: "CHEN BAILU", line: "What?" },
    { character: "FANG DASHENG", line: "Er---er---so hospitable, so straightforward." },
    { character: "CHEN BAILU", line: "Wasn't I straightforward before?" },
    { character: "FANG DASHENG", line: "Oh, I---I didn't mean it like that... I mean, you seem much more open-minded than before---" },
    { character: "CHEN BAILU", line: "You can't say I was ever narrow-minded! Oh, come on, you don't have to say nice things like that to me. " },
    { character: "CHEN BAILU", line: "I know what you're thinking: I'm rather too easy, too reckless. You probably think I'm a bit of a slut, don't you?"},
    // ... 继续添加更多对话 ...
    { character: "FANG DASHENG", line: "Er---yes. You did change a lot. You're just not the person I used to think you were. The way you talk, the way you walk, your attitude, your behavior, they've all changed. " },
    { character: "FANG DASHENG", line: "I've been sitting on the dance floor all night watching you. You're not the innocent girl you used to be. You've changed. You're a disappointment to me now. A huge one."},
    { character: "CHEN BAILU", line: "Disappointment?" },
    { character: "FANG DASHENG", line: "Yes, disappointment. I didn't expect I'd come here and you'd become such a easy woman." },
    { character: "CHEN BAILU", line: "Are you trying to lecture me? You know, I don't like to be lectured." },
    { character: "FANG DASHENG", line: "I'm not lecturing you. I just can't stand to see you like this. I've heard all sorts of things about you from thousands of miles away, and I don't believe it. "},
    { character: "FANG DASHENG", line: "I couldn't believe that the girl that I used to like the most could give people cause to speak of her as utterly worthless. " },
    { character: "FANG DASHENG", line: "So I come to see you, and I find you living in a place like this. a single woman, living by herself in an hotel,"},
    { character: "FANG DASHENG", line: "making friends with a lot of dubious characters, and this sort of behavior is, simply, immoral, decadent,- what do you expect me to say? "},
    { character: "CHEN BAILU", line: "How dare you call me that? In my room? How dare you say you're disappointed in me? What do you have to do with me? How dare you lecture me like that?" },
    { character: "FANG DASHENG", line: "Well, of course no, if you put it like that. But you should remember that you loved me very much. And you know what I'm here for this time." },
    { character: "CHEN BAILU", line: "What? Tell me." },
    { character: "FANG DASHENG", line: "I don't like to see you like this, playing dumb with me like this! You should know, I want you to come back with me." },
    { character: "CHEN BAILU", line: "Back? Back where? Surely you know there's no one in my family right now." },
    { character: "FANG DASHENG", line: "No, no, I mean come back to my place. I love you. I want you to marry me." },
    { character: "CHEN BAILU", line: "Oh, you were looking for me yesterday because you wanted matchmaking. Ah---" },
    { character: "FANG DASHENG", line: "I'm not playing matchmaker with you. I want you to marry me. That means I'll be your husband and you'll be my--" },
    { character: "CHEN BAILU", line: "Come on, come on, you don't have to explain. 'Marry' is a word we women know too well. But, my old friend, is that it?" },
    { character: "FANG DASHENG", line: "Tickets are right here. After dawn, we'll take the 10:00 a.m. train and we'll be out of here." },
    { character: "CHEN BAILU", line: "Let me see. You really bought two, one round trip and one single - oh, even a sleeper. That's very thoughtful of you." },
    { character: "FANG DASHENG", line: "You do agree to it, then. Then there's no problem." },
    { character: "CHEN BAILU", line: "No, wait a minute, I've got just one question---" },
    { character: "FANG DASHENG", line: "What?" },
    { character: "CHEN BAILU", line: "How much money do you have?" },
    { character: "FANG DASHENG", line: "I don't understand." },
    { character: "CHEN BAILU", line: "Don't understand? I'm asking if you can support me. Huh? Don't look at me like that! Don't you think I should talk like that? Hey, " },
    { character: "CHEN BAILU", line: "I want to be fed, don't you understand? I want to live comfortably, don't you understand? " },
    { character: "CHEN BAILU", line: "I want to go by car, wear nice clothes for a party, I want to play and dance, surely you understand that?"},
    { character: "FANG DASHENG", line: "Zhujun, listen, you have forgotten who you really are." },
    { character: "CHEN BAILU", line: "Are you asking me who I am? Listen to this: I was born into an intellectual family, then I was a student at Aihua Girls' School; " },
    { character: "CHEN BAILU", line: "I've been a leading light in society for a while, organizer of several big charity galas; ... Then my father died, my family got poorer."},
    { character: "CHEN BAILU", line: "I was a film star, a dancing star. With all these ups and downs, don't I not know who I am?"},
    { character: "FANG DASHENG", line: "You seem very pleased with yourself." },
    { character: "CHEN BAILU", line: "Well, why wouldn't I? I made it all on my own, without depending on family or friends, on my own to sink or swim. " },
    { character: "CHEN BAILU", line: "And here I am today, alive and kicking, as you can see for yourself. Why shouldn't I be pleased with myself?"},
    { character: "FANG DASHENG", line: "But do you think the money you've made this way is honorably come by?" },
    { character: "CHEN BAILU", line: "Dasheng, you're really a nerd. Do you really think the money made by your so-called 'honorable people' is come by honorably? " },
    { character: "CHEN BAILU", line: "I've got few of them here, all sorts: bankers, industrialists, officials. If you think their careers are honorable, the money I make this way is far more honorable."},
    { character: "FANG DASHENG", line: "I don't understand what you mean. Maybe our perceptions of honor--" },
    { character: "CHEN BAILU", line: "Well, perhaps our perceptions of honor are a little different. I haven't deliberately hurt anyone; I haven't snatched the food out of someone else's mouth. " },
    { character: "CHEN BAILU", line: "I like money and I try to make it, the same as they do, but I get my money by sacrificing my most precious thing. I have not cheated, I have not robbed; "},
    { character: "CHEN BAILU", line: "I have lived as others would willingly live, because I have sacrificed myself. I have done the most pitiful duty of a woman to a man, and I have enjoyed the rights that a woman should enjoy!"},
    { character: "FANG DASHENG", line: "Horrible, horrible - oh, you have no scruples now, no shame at all. Don't you know that when money gets the better of you, the most precious thing in life---love---will fly away like a bird?" },
    { character: "CHEN BAILU", line: "Love? What is love? You're such a kid! I'm done talking to you." },
    { character: "FANG DASHENG", line: "Okay, Zhujun, I see that your life for the past two years has already turned you half dead. But I'm here. I can't see you go on like this. I'm determined to convert you, I must---" },
    { character: "CHEN BAILU", line: "What? You want to convert me?" },
    { character: "FANG DASHENG", line: "Well, go ahead and laugh, I'm not going to argue with you much now. " },
    { character: "FANG DASHENG", line: "I know you think I'm a fool for travelling all the way from so far away to come here to you and say this whole lot of silly things. "},
    { character: "FANG DASHENG", line: "But I'm willing to make one more silly request. I wish you would still marry me. Please think about it carefully, and within twenty-four hours I hope you will give me a satisfactory answer."},
    { character: "CHEN BAILU", line: "Twenty-four hours, that scares the hell out of me. However, if my reply is unsatisfactory by your deadline, what will you do then? Force me to marry you?" },
    { character: "FANG DASHENG", line: "Then, er, then---" },
    { character: "CHEN BAILU", line: "Then what?" },
    { character: "FANG DASHENG", line: "If you won't marry me---" },
    { character: "CHEN BAILU", line: "What?" },
    { character: "FANG DASHENG", line: "Then perhaps I'll kill myself." },
    { character: "CHEN BAILU", line: "What? So you've picked that up too?" },
    { character: "FANG DASHENG", line: "No, no, I'm not killing myself. Don't worry, I'm not going to kill myself for a woman. I'll go, far away." },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "Yeah, now you're talking like a grow-up! Well, my silly boy, then you won't have to wait another 24 hours!" },
    { character: "FANG DASHENG", line: "What?" },
    { character: "CHEN BAILU", line: "I can give you my answer now." },
    { character: "FANG DASHENG", line: "Now? No, wait. I'm a little panicked. Don't say anything now. I need to calm down." },
    { character: "CHEN BAILU", line: "Let me pour you a cup of herbal tea for you to calm down?" },
    { character: "FANG DASHENG", line: "No, that won't be necessary." },
    { character: "CHEN BAILU", line: "Have a cigarette then." },
    { character: "FANG DASHENG", line: "It's the third time I'm telling you, I don't smoke. Come on. I'm over it now. Go ahead." },
    { character: "CHEN BAILU", line: "You're calm now." },
    { character: "FANG DASHENG", line: "Yes!" },
    { character: "CHEN BAILU", line: "You may go now." },
    { character: "FANG DASHENG", line: "What?" },
    { character: "CHEN BAILU", line: "I won't marry you, under any circumstances whatever." },
    { character: "FANG DASHENG", line: "Why---why not?" },
    { character: "CHEN BAILU", line: "For no reason at all! You really are impossible! You can't find reasons for such things. Don't you understand?" },
    { character: "FANG DASHENG", line: "So you have no feelings for me at all?" },
    { character: "CHEN BAILU", line: "You can say that." },
    { character: "FANG DASHENG", line: "What're you doing?" },
    { character: "CHEN BAILU", line: "Ringing the bell." },
    { character: "FANG DASHENG", line: "What for?" },
    { character: "CHEN BAILU", line: "If you really want to kill yourself, I'll have some witnesses." },
    { character: "FANG DASHENG", line: "Did you mean what you said just now, without a little bit of emotion?" },
    { character: "CHEN BAILU", line: "Do I still look like the kind of people with emotions?" },
    { character: "FANG DASHENG", line: "Zhujun!" },
    { character: "CHEN BAILU", line: "What now?" },
    { character: "FANG DASHENG", line: "We must say goodbye now." },
    { character: "CHEN BAILU", line: "Yes, goodbye. It's a goodbye for always Fang Dasheng. Farewell." },
    { character: "FANG DASHENG", line: "Yes, for always." },
    { character: "CHEN BAILU", line: "Are you really leaving?" },
    { character: "FANG DASHENG", line: "Yes." },
    { character: "CHEN BAILU", line: "I suppose you forgot your return ticket, then." },
    { character: "FANG DASHENG", line: "Oh!" },
    { character: "CHEN BAILU", line: "You're really leaving?" },
    { character: "FANG DASHENG", line: "Yes, Zhujun!" },
    { character: "CHEN BAILU", line: "What's the matter with you? Silly boy, having tears hanging. You're not ashamed. "},
    { character: "CHEN BAILU", line: "Well, my poor thing, you've made me cry, eh? I'll wipe it off for you. Look, such an adult, what a shame! "},
    { character: "CHEN BAILU", line: " No more crying, no more tears! Dasheng, to be honest, don't be such a kid. Do you really think you can just go away?"},
    { character: "FANG DASHENG", line: "Why?" },
    { character: "CHEN BAILU", line: "Aren't these your tickets?" },
    { character: "FANG DASHENG", line: "Yes, what about it?" },
    { character: "CHEN BAILU", line: "Now watch, once like this, and then like this. I'll keep them for you, all right?" },
    { character: "FANG DASHENG", line: "You, why did you---" },
    { character: "CHEN BAILU", line: "Don't you understand?" },
    { character: "FANG DASHENG", line: "So you accepted me after all, Zhujun." },
    { character: "CHEN BAILU", line: "No, no, you misunderstood. I didn't accept you. I was tearing up your ticket, I wasn't tearing up my contract of sale. I'm sold to this place for life." },
    { character: "FANG DASHENG", line: "Then why won't you let me go?" },
    { character: "CHEN BAILU", line: "Do you think you're the only one in the world with feelings? Do I have to hate you because I can't marry you? " },
    { character: "CHEN BAILU", line: "Don't you even have the affection to spend a couple of days with me and talk about the old days? You're so old-fashioned. "},
    { character: "CHEN BAILU", line: "Can't we be good friends without getting married? Surely something remains of the feelings we used to have for each other, something we'd like to share?"},
    { character: "CHEN BAILU", line: "The minute you got through the door, you've been looking askance at me. You said I was wrong about this and that. You lectured me, and you scolded me. " },
    { character: "CHEN BAILU", line: "You looked down on me, and you demanded that I marry you at once. And then you demanded an answer within twenty-four hours, and then you want me to go with you immediately. "},
    { character: "CHEN BAILU", line: "A woman could be as submissive as a sheep, but she should not be so pitiful as to be in such a state."},
    { character: "FANG DASHENG", line: "I've always been like that; I'm not good at declaring love. If you want me to say something nice on my knees, I just can't do it." },
    { character: "CHEN BAILU", line: "Yeah, so it won't hurt you to get some more practice with me. In a couple days, you'll be able to do it. Well, would you like to spend a day or two talking with me?" },
    { character: "FANG DASHENG", line: "But what about?" },
    { character: "CHEN BAILU", line: "There's a lot to talk about, and I can show you around the city and entertain you. You can see how the people here live." },
    { character: "FANG DASHENG", line: "No, don't bother. The people here are ghosts. I don't need to see them. And anyway, my luggage was already sent to the station yesterday." },
    { character: "CHEN BAILU", line: "Really?" },
    { character: "FANG DASHENG", line: "You know I never lie." },
    { character: "CHEN BAILU", line: "Fusheng." },
    // ... 继续添加更多对话 ...
    { character: "WANG FUSHENG", line: "Don't worry, Miss Chen. Your bed will be cleaned up right away." },
    { character: "CHEN BAILU", line: "No, not that. Let me ask you something, when I left, I told you to get the luggage from the Oriental Hotel ---er---the station. Did you bring it?" },
    { character: "WANG FUSHENG", line: "You mean Mr. Fang's. Yes, I've fetched it from the Hotel." },
    { character: "FANG DASHENG", line: "Zhujun, how dare you remove my luggage from my hotel!" },
    { character: "CHEN BAILU", line: "Well, there it is. I dare remove your luggage from your hotel. So much for your never telling lies, you silly. Which suite did you put it in?" },
    { character: "WANG FUSHENG", line: "Number 24, in the east." },
    { character: "CHEN BAILU", line: "Is it the best one?" },
    { character: "WANG FUSHENG", line: "The best one in the hotel except this one of yours." },
    { character: "CHEN BAILU", line: "Good. Will you show Mr. Fang to his suite, then? If Mr. Fang doesn't see fit, tell me and I'll let him have my room." },
    { character: "WANG FUSHENG", line: "Yes, Miss Chen." },
    { character: "FANG DASHENG", line: "But Zhujun, this isn't appropriate." },
    { character: "CHEN BAILU", line: "This place is full of inappropriate things. This time I'm inviting you to look around, " },
    { character: "CHEN BAILU", line: "so that you can get rid of your old-fashioned narrow-mindedness. See more of it and then it's appropriate for you."},
    { character: "FANG DASHENG", line: "No, Zhujun. This needs thinking about." },
    { character: "CHEN BAILU", line: "No more nonsense. Get out! Fusheng! Fusheng! Fusheng!" },
    { character: "FANG DASHENG", line: "I can never sleep in a hotel like this." },
    { character: "CHEN BAILU", line: "If you can't sleep, I have sleeping pills here. Take a couple and you won't mind the noise anyhow. You want some?" },
    { character: "FANG DASHENG", line: "Stop kidding. I'm telling you, I'd hate to look at this place." },
    { character: "CHEN BAILU", line: "No, you have to see it. I want you to see it. Take him to his suite. Hurry up and take a bath and get a good night's sleep. " },
    { character: "CHEN BAILU", line: "When you get up, change into clean clothes and I'll take you out. Now come on, there's a good boy. "},
    { character: "CHEN BAILU", line: "Behave. Did you hear me? Goodnight. Listen, it's really late. Come on, go to sleep."},
    { character: "CHEN BAILU", line: "Thief!" },
    { character: "THE FIGURE", line: "Don't scream! Don't scream!" },
    { character: "CHEN BAILU", line: "Who's that? Who are you?" },
    { character: "THE FIGURE", line: "Miss! Miss!" },
    { character: "CHEN BAILU", line: "What are you doing here?" },
    { character: "THE FIGURE", line: "I...I" },
    { character: "CHEN BAILU", line: "Oh, you poor thing, just a shrimp after all." },
    { character: "THE SHRIMP", line: "Yes, yes, miss." },
    { character: "CHEN BAILU", line: "What are you doing here, shrimp? Stealing? Tell me!" },
    { character: "THE SHRIMP", line: "I...I'm not stealing." },
    { character: "CHEN BAILU", line: "Then who do you steal these clothes from?" },
    { character: "THE SHRIMP", line: "I stole them from my mother." },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "Who's your mother?" },
    { character: "THE SHRIMP", line: "My mother! I don't even know who my mother is." },
    { character: "CHEN BAILU", line: "You silly child. How can you not know who your mother is. Where does your mother live?" },
    { character: "THE SHRIMP", line: "Upstairs." },
    { character: "CHEN BAILU", line: "Upstairs. Oh, you're from upstairs, poor thing, who told you to run out?" },
    { character: "THE SHRIMP", line: "No one. I ran out myself." },
    { character: "CHEN BAILU", line: "Why?" },
    { character: "THE SHRIMP", line: "Because...they..." },
    { character: "CHEN BAILU", line: "What?" },
    { character: "THE SHRIMP", line: "The night before last..." },
    { character: "CHEN BAILU", line: "Come on, it's okay." },
    { character: "THE SHRIMP", line: "They asked me to sleep with a dark fat man the night before last, and I was so scared, I wouldn't do it, and they--" },
    { character: "CHEN BAILU", line: "They beat you." },
    { character: "THE SHRIMP", line: "Yes, with a whip. Last night they brought me here again and the dark fat man came again. " },
    { character: "THE SHRIMP", line: "I was so scared of him that I started shouting, and the man went off in a rage and they---"},
    { character: "CHEN BAILU", line: "They beat you again." },
    { character: "THE SHRIMP", line: "No, there was someone else in the next room and they were afraid someone will hear." },
    { character: "THE SHRIMP", line: "They gagged me, pinched me, and stuck me with a opium needle. Look, please look!" },
    { character: "CHEN BAILU", line: "What's the matter?" },
    { character: "THE SHRIMP", line: "My legs also got stuck, Miss." },
    { character: "CHEN BAILU", line: "God! Your arm..." },
    { character: "THE SHRIMP", line: "It's okay, Miss. Please don't cry. They were afraid I might run away, so they took my clothes and made me stay in bed." },
    { character: "CHEN BAILU", line: "What were they doing when you ran out?" },
    { character: "THE SHRIMP", line: "Smoking and playing mahjong in the next room. Then I got out of bed quietly and put on my mother's clothes." },
    { character: "CHEN BAILU", line: "Why didn't you run right out?" },
    { character: "THE SHRIMP", line: "Where should I go? I don't know anybody. I've got no money." },
    { character: "CHEN BAILU", line: "How about your mom?" },
    { character: "THE SHRIMP", line: "She's upstairs." },
    { character: "CHEN BAILU", line: "No, I mean your own mother, the one who gave birth to you." },
    { character: "THE SHRIMP", line: "Oh. She's dead, a long time ago." },
    { character: "CHEN BAILU", line: "And your father?" },
    { character: "THE SHRIMP", line: "He died last month." },
    { character: "CHEN BAILU", line: "Oh! But why here? They can find you easily." },
    { character: "THE SHRIMP", line: "No, no, no! You must help me! Please don't let them find me, they'll beat me to death. Miss, Miss, please!" },
    { character: "CHEN BAILU", line: "Get up. I didn't say to send you back. Just sit tight and let us think of a solution." },
    { character: "THE SHRIMP", line: "Thank you. Thank you, Miss." },
    { character: "CHEN BAILU", line: "What are you doing?" },
    { character: "THE SHRIMP", line: "Close the door so that no one will come in." },
    { character: "CHEN BAILU", line: "Oh, it's okay. Don't be afraid. But didn't you want to get out?" },
    { character: "THE SHRIMP", line: "Yes." },
    { character: "CHEN BAILU", line: "Where were you going?" },
    { character: "THE SHRIMP", line: "I was going back." },
    { character: "CHEN BAILU", line: "Back? Back to them?" },
    { character: "THE SHRIMP", line: "Yes." },
    { character: "CHEN BAILU", line: "Why?" },
    { character: "THE SHRIMP", line: "I'm hungry, so hungry. I figured maybe they didn't know that I ran out. " },
    { character: "THE SHRIMP", line: "I know they'll beat me after dawn, but in a little they'll give me some porridge to eat. Other people won't even give me that."},
    { character: "CHEN BAILU", line: "You didn't eat yet?" },
    { character: "THE SHRIMP", line: "If I don't have anything more in my stomach, I'll starve to death. They don't want me to die, I know that." },
    { character: "CHEN BAILU", line: "How long have you not eaten?" },
    { character: "THE SHRIMP", line: "Over a day. They said they were not going to let me eat anything until the fat black guy was happy." },
    { character: "CHEN BAILU", line: "Here are some biscuits for you." },
    { character: "THE SHRIMP", line: "Thank you, Miss!" },
    { character: "CHEN BAILU", line: "Eat slowly. Don't choke." },
    { character: "THE SHRIMP", line: "Is this all?" },
    { character: "CHEN BAILU", line: "There's more if you want. It's okay. Does hunger drive a person to this?" },
    { character: "THE SHRIMP", line: "Miss!" },
    { character: "CHEN BAILU", line: "Who is it?" },
    { character: "WANG FUSHENG", line: "It's me, Fusheng." },
    { character: "THE SHRIMP", line: "Miss, He..." },
    { character: "CHEN BAILU", line: "Don't be frightened. He's only the waiter who serves people." },
    { character: "WANG FUSHENG", line: "Miss, the manager of the Dafeng Bank came here three times last night." },
    { character: "CHEN BAILU", line: "I know, I know." },
    { character: "WANG FUSHENG", line: "He's still here." },
    { character: "CHEN BAILU", line: "Still here? Why?" },
    // ... 继续添加更多对话 ...
    { character: "WANG FUSHENG", line: "Well, you know there's a big building going up next to this hotel, right? I think Mr.Pan is probably talking to his secretary about it. " },
    { character: "WANG FUSHENG", line: "But he said when you came back I was to go and ask him here."},
    { character: "CHEN BAILU", line: "If they want to build a building there's no reason why they shouldn't. I just don't see why they would have to come here in the middle of the night to discuss it." },
    { character: "WANG FUSHENG", line: "That's right." },
    { character: "CHEN BAILU", line: "Why didn't you tell me this just now?" },
    { character: "WANG FUSHENG", line: "Well, I thought Mr. Fang was still here---" },
    { character: "CHEN BAILU", line: "Oh, then don't send Mr. Pan here. Tell him I'm off to bed." },
    { character: "WANG FUSHENG", line: "Why don't you see him? Mr. Pan is the manager of a big bank---" },
    { character: "CHEN BAILU", line: "Stay out of it. I don't want to see him. Do you hear me?" },
    { character: "WANG FUSHENG", line: "But, miss, please don't get angry. Listen, and don't worry! Here are some bills here. 654 dollars forty for Meifeng Jewelers. " },
    { character: "WANG FUSHENG", line: "355 dollars fifty-five for Yongchang Silk Company. 229 dollars seventy-six for the hotel. 117 dollars seventy for the Hongsheng Photographic Studio. "},
    { character: "WANG FUSHENG", line: "91 dollars thirteen for the Jiuhuachang Shoe Shop, and 76 dollars fifty for the week's cars---oh, and also---"},
    { character: "CHEN BAILU", line: "Stop, stop reading. I don't want to listen!" },
    { character: "WANG FUSHENG", line: "But, Miss, it's not that I don't want to serve you, but I can't keep putting your creditors off like this every day." },
    { character: "WANG FUSHENG", line: "I can't go down without any more cash today no matter what you say."},
    { character: "CHEN BAILU", line: "Money, money, it's always money! Why do you keep trying to scare me with that line!" },
    { character: "WANG FUSHENG", line: "I wouldn't even dare, Miss. But things are tight these days. You don't know today whether tomorrow---" },
    { character: "CHEN BAILU", line: "I never asked anyone to give me money. It's always the others who send me money themselves." },
    { character: "WANG FUSHENG", line: "There' no doubt about your good standing, Miss. But---" },
    { character: "CHEN BAILU", line: "Well, I'll think of something to reassure them." },
    { character: "WANG FUSHENG", line: "Alright. Miss, what's this little girl going here?" },
    { character: "CHEN BAILU", line: "It's none of your business." },
    { character: "WANG FUSHENG", line: "I seem to recognize her. Now Miss, I advise you to stay out of this ." },
    { character: "CHEN BAILU", line: "Why?" },
    { character: "WANG FUSHENG", line: "Someone's looking for her outside." },
    { character: "CHEN BAILU", line: "Who?" },
    { character: "WANG FUSHENG", line: "A gang of toughs from upstairs, dressed in black and wearing felt hats crookedly, did all the fighting." },
    { character: "THE SHRIMP", line: "Ah! Miss! Master, you must save me!" },
    { character: "WANG FUSHENG", line: "Keep away from me." },
    { character: "CHEN BAILU", line: "Close the door! Lock it!" },
    // ... 继续添加更多对话 ...
    { character: "WANG FUSHENG", line: "But Miss---" },
    { character: "CHEN BAILU", line: "Lock the door." },
    { character: "WANG FUSHENG", line: "Miss. We can never hide her. Her mother and father are looking for her in the building." },
    { character: "CHEN BAILU", line: "Then we'll give them some money they'll be satisfied." },
    { character: "WANG FUSHENG", line: "You're generous again. Give them some money? How many thousands you've got?" },
    { character: "CHEN BAILU", line: "Why?" },
    { character: "WANG FUSHENG", line: "Give them some money now and they'll soak every penny you have." },
    { character: "CHEN BAILU", line: "Then we'd---" },
    { character: "WANG FUSHENG", line: "Quiet! There's someone outside. They're here." },
    { character: "THE SHRIMP", line: "Ah, Miss!" },
    { character: "CHEN BAILU", line: "If you make one more sound, I'll push you outside." },
    { character: "THE SHRIMP", line: "No, no!" },
    { character: "CHEN BAILU", line: "Be quiet. Listen." },
    { character: "BLANCK SAN'S VOICE", line: "This little bitch, she's more trouble than she's worth, throwing away the chance of a lifetime and running away. I'm damned if I know what fathered her." },
    { character: "WOMAN'S VOICE", line: "Now Master Jin is pissed off at this kid and he went off." },
    { character: "BLANCK SAN'S VOICE", line: "What? Jin got his eye on her?" },
    { character: "WOMAN'S VOICE", line: "I ask you, here's someone rolling in money comes along and all this heartless child can do is to bolt. " },
    { character: "WOMAN'S VOICE", line: "That's going to take some explaining away, I can tell you."},
    { character: "San'S VOICE", line: "You bloody well clear out of it. The kid ran way, because you were not keeping an eye on her, and all you can do is to shut your goddamn mouth. "},
    { character: "San'S VOICE", line: "Hey, she's not going to run out, is she?" },
    { character: "SECOND MAN'S VOICE", line: "No, not a chance. She ran away in Mama's clothes, a single coat. Where is she going to go in this sheer cold?" },
    { character: "WOMAN'S VOICE", line: "That's right, she ran away in my clothes. Where would she have gone? But there's no sight of her on the first and second floor. You think she'd---" },
    { character: "THIRD MAN'S VOICE", line: "The waiter on this floor said he's just seen her. Then where could she have gone?" },
    { character: "BLACK MAN'S VOICE", line: "Then she must be on this floor. So let's get on with it and find her." },
    { character: "WOMAN'S VOICE", line: "She won't escape, this little bitch." },
    { character: "MANY MEN OUTSIDE", line: "Don't worry! Mama! She's right here. Let's split up. We'll find it." },
    { character: "CHEN BAILU", line: "They've gone?" },
    { character: "WANG FUSHENG", line: "Yes, probably over there." },
    { character: "CHEN BAILU", line: "Let me have a look." },
    { character: "THE SHRIMP", line: "Miss! Miss!" },
    // ... 继续添加更多对话 ...
    { character: "WANG FUSHENG", line: "Don't mess with them. People like that can be nasty if you mess with them. Only fools will go looking for trouble." },
    { character: "CHEN BAILU", line: "What do you mean?" },
    { character: "THE SHRIMP", line: "They don't go around with no weapons, any of them. They get their living by risking their necks." },
    { character: "CHEN BAILU", line: "But surely they have some respects for law! After beating a child like this, look! " },
    { character: "CHEN BAILU", line: "They stabbed her with opium-needles, causing her to bleed! I can sue them if it gets heated."},
    { character: "WANG FUSHENG", line: "Sue them? How? They're in with all the people who matter here. Even if you won your case, what chance would you have when they came to even the score?" },
    { character: "CHEN BAILU", line: "But I can't send this kid to them!" },
    { character: "THE SHRIMP", line: "No, don't, Miss." },
    { character: "WANG FUSHENG", line: "It's an awkward business. I think you'd better be sensible and send the kid back. " },
     { character: "WANG FUSHENG", line: "I heard she slapped Master Jin on the face and pissed him off. Don't you know that?"},
    { character: "CHEN BAILU", line: "Master Jin! Who's Master Jin?" },
    { character: "THE SHRIMP", line: "It's that fat black guy." },
    { character: "WANG FUSHENG", line: "Master Jin! The God of Wealth himself, a man rolling in money and in influence. These gangsters are all under his command. You never heard of him?" },
    { character: "CHEN BAILU", line: "What? Master Jin! It was him? What would he be doing here, in this hotel?" },
    { character: "WANG FUSHENG", line: "If he's boring at home and comes here for a night out, why shouldn't he? After all, he's got money." },
    { character: "CHEN BAILU", line: "Jin... To think you'd fall into the hands of a monster like that. You slapped his face, right, Shrimp?" },
    { character: "THE SHRIMP", line: "You mean the dark fat guy? Yes, he was trying to hold me, and I couldn't avoid it. So I hit him, slapped him hard across his fat face!" },
    { character: "CHEN BAILU", line: "You slapped Jin!" },
    { character: "THE SHRIMP", line: "But, Miss, I'll never hit him again, never again." },
    { character: "CHEN BAILU", line: "Well done! Well done! I hope it hurt him!" },
    { character: "WANG FUSHENG", line: "Miss, let me make it clear that I'm not in on this. " },
    { character: "WANG FUSHENG", line: "If you want to be the saint and take charge of this kid, you'll do it on your own. It's got nothing to do with me. If they ask me later---"},
    { character: "CHEN BAILU", line: "Then you didn't see her!" },
    { character: "WANG FUSHENG", line: "Didn't see her?" },
    { character: "CHEN BAILU", line: "You'll have to say that." },
    { character: "WANG FUSHENG", line: "But---" },
    { character: "CHEN BAILU", line: "If anything happens, I'll take care of it." },
    { character: "WANG FUSHENG", line: "Alright, alright. You take care of it then. Witness the electric light above and the floor beneath that you said it yourself." },
    { character: "CHEN BAILU", line: "Of course, when I say something, I really mean it. Now go send Mr. Pan in." },
    { character: "WANG FUSHENG", line: "Didn't you say just now that you didn't want to see him?" },
    { character: "CHEN BAILU", line: "Do as you're told and cut the crap." },
    { character: "WANG FUSHENG", line: "Very well---Very well---Very well---" },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "Are you finished eating now?" },
    { character: "THE SHRIMP", line: "I only ate two biscuits." },
    { character: "CHEN BAILU", line: "What?" },
    { character: "THE SHRIMP", line: "I...I... I'm not full." },
    { character: "CHEN BAILU", line: "Eat as much as you can." },
    { character: "THE SHRIMP", line: "No, I'm all good." },
    { character: "CHEN BAILU", line: "Why?" },
    { character: "THE SHRIMP", line: "I'm scared, I'm so scared." },
    { character: "CHEN BAILU", line: "Don't cry...Don't cry." },
    { character: "THE SHRIMP", line: "Miss, you won't send me back to them, will you?" },
    { character: "CHEN BAILU", line: "No, I won't. Now stop crying. Listen! Someone's outside!" },
    { character: "PAN YUETING", line: "Bailu, I knew you'd send for me! I've been waiting all night for you. Fortunately, Li Shiqing turned up to see me about some bank business." },
    { character: "PAN YUETING", line:"Otherwise, I wouldn't have known how to get by. I sent someone up to you a couple of times, but you're not back. "},
    { character: "PAN YUETING", line:"I asked you to dine with me and you wouldn't; I asked you to go dancing with me and you wouldn't. But I knew you'd send for me sooner or later." },
    { character: "CHEN BAILU", line: "You're this sure of your charms, aren't you?" },
    { character: "PAN YUETING", line: "It's a pity you didn't see me when I was young, when--- What are you doing here, get out!" },
    { character: "WANG FUSHENG", line: "Yes, Mr. Pan." },
    { character: "PAN YUTING", line: "I knew you miss me, right? Say that you miss me." },
    { character: "CHEN BAILU", line: "Yes, I miss you---" },
    { character: "PAN YUETING", line: "I know. You're so kind." },
    { character: "CHEN BAILU", line: "Yes, I was thinking of you doing a favor for me." },
    { character: "PAN YUETING", line: "A favor again. --- Is that all you can think of when you see me? All these trivial matters." },
    { character: "CHEN BAILU", line: "How did you know?" },
    { character: "PAN YUETING", line: "Fusheng told me everything." },
    { character: "CHEN BAILU", line: "Are you in or not?" },
    { character: "PAN YUETING", line: "Well, so this is the little shrimp." },
    { character: "THE SHRIMP", line: "Yes, Master." },
    { character: "CHEN BAILU", line: "Look at the poor little thing, she---" },
    { character: "PAN YUETING", line: "Alright, I know. That's what always happens." },
    { character: "CHEN BAILU", line: "Yueting, are you in or not?" },
    { character: "PAN YUETING", line: "I'm in! I'm in!" },
    { character: "CHEN BAILU", line: "Well Shrimp, why are you not thanking Mr. Pan!" },
    { character: "PAN YUETING", line: "Come on, don't do that. Bailu, you're such a sweet burden to me." },
    { character: "CHEN BAILU", line: "Listen! They seem to be right at the door. Shrimp, go in that room." },
    // ... 继续添加更多对话 ...
    { character: "San'S VOICE", line: "This door?" },
    { character: "SECOND MAN'S VOICE", line: "That's the one." },
    { character: "CHEN BAILU", line: "They probably mean my door." },
    { character: "PAN YUETING", line: "Yes." },
    { character: "San'S VOICE", line: "You sure this was the door you saw her go in?" },
    { character: "SECOND MAN'S VOICE", line: "Yes." },
    { character: "San'S VOICE", line: "And she didn't come out?" },
    { character: "WOMAN'S VOICE", line: "What's the matter with you? Why are you hesitating at the door?" },
    { character: "THIRD MAN'S VOICE", line: "No, we have to be sure. We can't make a mistake." },
    { character: "CHEN BAILU", line: "Yueting, you can't wait for them to come in. You have to open the door, go out and tell them to clear off." },
    { character: "PAN YUETING", line: "They probably know me, these guys. There shouldn't be much trouble getting rid of them." },
    { character: "CHEN BAILU", line: "Good, Yueting. Thank you, thank you. You're a good guy." },
    { character: "PAN YUETING", line: "That's the first time you thanked me since I've known you." },
    { character: "CHEN BAILU", line: "Because it's the first time you've been the good guy." },
    { character: "PAN YUETING", line: "There you go again, Bailu, making fun of me, you---" },
    { character: "CHEN BAILU", line: "Stop! Just go and clear them off." },
    { character: "PAN YUETING", line: "Alright." },
    { character: "CHEN BAILU", line: "But Yueting, you do realize that it was Jin who's got an eye on the girl." },
    { character: "PAN YUETING", line: "Jin? What?" },
    { character: "CHEN BAILU", line: "She offended Jin." },
    { character: "PAN YUETING", line: "What, this is the girl Jin's taken a fancy to?" },
    { character: "CHEN BAILU", line: "Didn't Fusheng tell you that?" },
    { character: "PAN YUETING", line: "No, no. Whew, you nearly made a mistake." },
    { character: "CHEN BAILU", line: "So you changed your mind, Yueting?" },
    { character: "PAN YUETING", line: "Don't you realize, Bailu, that this man Jin has all the connections in the world and he's too arbitrary?" },
    { character: "CHEN BAILU", line: "You're calling it all, then?" },
    { character: "PAN YUETING", line: "It's not that I don't want to do it, I can't. Anyway, she's just a country kid, why do you have to---" },
    { character: "CHEN BAILU", line: "Yueting, don't stop me. If you're calling it off, then do as it pleases you, but don't stop me." },
    { character: "PAN YUETING", line: "There, there, there's no need to be like this." },
    { character: "THIRD MAN'S VOICE", line: "Knock! She must be here!" },
    { character: "San'S VOICE", line: "Why?" },
    { character: "THIRD MAN'S VOICE", line: "Look, Mama's handkerchief. That girl was in here coat when she ran off, wasn't she?" },
    { character: "WOMAN'S VOICE", line: "That's right, that's my handkerchief." },
    { character: "San'S VOICE", line: "Then she must be behind this door. She must be here. Open the door. Open the door!" },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "Try not be afraid!" },
    { character: "PAN YUETING", line: "Just ignore them!" },
    { character: "VOICES OUTSIDE", line: "Open the door. We're looking for someone." },
    { character: "CHEN BAILU", line: "Yueting, go inside that room and save yourself the trouble. I'll open the door." },
    { character: "PAN YUETING", line: "Don't, Bailu." },
    { character: "CHEN BAILU", line: "Go in there. Go in there. I'll be really mad at you." },
    { character: "PAN YUETING", line: "Alright, I'll go in there." },
    { character: "CHEN BAILU", line: "Hurry up." },
    { character: "CHEN BAILU", line: "Come in! What do you want?" },
    { character: "San", line: "None of your business! Come in. Now come in, all of you, and search!" },
    { character: "CHEN BAILU", line: "Stop! All of you? Did anyone said anything about all of you coming in? Who do you think you are? "},
    { character: "CHEN BAILU", line: "If you're so unreasonable, the boss of the manor's here! Are you looking for contraband? If it's opium you're looking for you'll find plenty here, and guns too! "},
    { character: "CHEN BAILU", line: "I'm not messing with you guys! I've got five hundred taels of opium and there I've got eighty guns. Just tell me what do you want! "},
    { character: "CHEN BAILU", line: "That much should be enough for you to amuse yourselves. Come in, Gentlemen! Why don't you come in? Why are you so scared?" },
    { character: "THIRD MAN", line: "In we go, then. What's scaring us?" },
    { character: "San", line: "Get out, you idiot. Who said you could come in?" },
    { character: "THIRD MAN", line: "Well, getting out I am, if that's what you want. It's the same to me!" },
    { character: "San", line: "Don't, don't upset yourself. No need to fly into such a rage! Don't think we'd come here and disturb you without a good reason. "},
    { character: "San", line:"We've lost a child, a newcoming girl here. We just came here to see if she's hiding somewhere, in case she scares you later."},
    { character: "CHEN BAILU", line: "Oh, I see. So all you people are here just for a little girl!" },
    { character: "San", line: "Then you probably have seen her coming in." },
    { character: "CHEN BAILU", line: "Sorry, not a clue." },
    { character: "San", line: "But we found a handkerchief that she lost at your door." },
    { character: "CHEN BAILU", line: "What can I do if she will go and drop it?" },
    { character: "San", line: "Ah, but someone saw her come in here just a while back." },
    { character: "CHEN BAILU", line: "If she's been in my suite I'll tell you this right now: if she's stolen something, you must pay for it." },
    { character: "San", line: "Cut out the funny stuff, please. We're probably all in the same sort, so you might give me a helping hand. I can see that you and the Master Jin must also be--" },
    { character: "CHEN BAILU", line: "Master Jin? Oh, are you friends of Master Jin, too?" },
    { character: "San", line: "Oh, certainly not up to being his friends. We're just running some small errands for him." },
    { character: "CHEN BAILU", line: "Perfect. Master Jin just told me to tell you to clear off." },
    { character: "San", line: "What? Did he really---" },
    { character: "CHEN BAILU", line: "Master Jin's right here, as it happens." },
    { character: "San", line: "Right here? But we just saw him off from the hotel." },
    { character: "CHEN BAILU", line: "But you didn't know that he came back." },
    { character: "San", line: "He came back? Then we'd better see him and tell him how we're getting on. Is that correct?" },
    { character: "VOICES OUTSIDE", line: "Right! We have to see him." },
    // ... 继续添加更多对话 ...
    { character: "CHEN BAILU", line: "No! Master Jin didn't want to see anyone." },
    { character: "San", line: "He won't refuse to see me. I want to see him. I have to!" },
    { character: "CHEN BAILU", line: "Well, you can't." },
    { character: "San", line: "It's not a matter of can't, it's a matter of must. He's probably in this room." },
    { character: "CHEN BAILU", line: "Yes, you may go in that room, so long as you don't come in this." },
    { character: "San", line: "Oh, so Mrs. Jin is up to her funny stuff again. Out of my way!" },
    { character: "CHEN BAILU", line: "You'll lose your head. Master Jin, Master Jin, come out and teach these idiots a lesson." },
    { character: "PAN YUETING", line: "What's all this noise, Bailu? Master Jin's asleep. It's you, San! Why are you here?" },
    { character: "San", line: "Oh, Master Pan, you're here too." },
    { character: "PAN YUETING", line: "I came here with Master Jin to rest for a moment and have a smoke, and here are you, coming in to start a revolution. What are you up to?" },
    { character: "San", line: "Well, so it is Master Jin here. Er, he's having a sleep here?" },
    { character: "PAN YUETING", line: "What, you want to come in and chat with him? Then please come in and sit down! I'll prepare a bead of opium and get Master Jin up for you, okay?" },
    { character: "San", line: "Don't make fun of us like this, Master Pan." },
    { character: "PAN YUETING", line: "Won't sit down, huh? Not even those gentlemen at the door?" },
    { character: "San", line: "No, no, we've still got a duty, and---" },
    { character: "PAN YUETING", line: "Excellent. If so, then get the hell out of here and cut the crap!" },
    { character: "San", line: "Okay, Master Pan, but please don't get angry. Please forgive us if we ever offend you. What are you looking at? "},
    { character: "San", line: "Get out you rabble! Aren't you all fucking deaf? See? What can you do with people like that? " },
    {character: "San", line: "Master Pan, when Master Jin wakes up later, please don't tell him that we've been here. "},
    {character: "San", line: "And you, Miss, please put in a good word for us, and don't say a word of what happened here. "},
     {character: "San", line: "It was a joke on my part. I don't deserve to live. I deserve to be hanged for it."},
    { character: "CHEN BAILU", line: "All right, now get out!" },
    { character: "San", line: "You're not angry with us any longer? Okay, we're getting out now." },
    { character: "CHEN BAILU", line: "That's that. First time I've done anything so awesome!" },
    { character: "PAN YUETING", line: "That's that. First time I've done anything so absurd." },
    { character: "CHEN BAILU", line: "Well, now you can go and ask the almighty Master Jin to resume his throne." },
    { character: "PAN YUETING", line: "Humph! It's easier to raise the Devil than to send him away. " },
    { character: "PAN YUETING", line: "It's easy enough to get rid of them with some bluff like that, but next time we run into him there's going to be hell to pay."},
    { character: "CHEN BAILU", line: "We won't worry about the future until it comes! Anyway, it was fun!" },
    { character: "PAN YUETING", line: "Fun?" },
    { character: "CHEN BAILU", line: "I think everything could be fun. Don't you agree? I'm tired. Look! Look at that!" },
    { character: "PAN YUETING", line: "What?" },
    { character: "CHEN BAILU", line: "The sun's up." },
    // ... 继续添加更多对话 ...
    { character: "PAN YUETING", line: "So the sun's up. Why all the shouting about it?" },
    { character: "CHEN BAILU", line: "Look how blue the sky is! And the clouds! Hey, listen to the sparrows! It's spring! Oh!"}, 
    { character: "CHEN BAILU", line: " I love the sun, I love the spring, I love being young. I love myself. Oh, I love it!" },
    { character: "PAN YUETING", line: "I don't see what all the fuss is about. Bailu, it's too cold in here. You'll be frozen. Let me close the window." },
    { character: "CHEN BAILU", line: "No, I don't want it shut! I don't want it shut!" },
    { character: "PAN YUETING", line: "All right, all right. Then we'll leave it open. Child, you're a great trial to me. I've never been so considerate to my own daughter." },
    { character: "CHEN BAILU", line: "There's no surprise. Would you be so considerate if I were your daughter?" },
    { character: "PAN YUETING", line: "Well said, a very penetrating remark. Come on, shut the window or I'll be catching... catching... there, I already caught a cold." },
    { character: "CHEN BAILU", line: "You silly boy, why didn't you say so before?" },
    { character: "PAN YUETING", line: "Now you'll shut the window." },
    { character: "CHEN BAILU", line: "No, I won't do that, I'll give you some more clothes to put on. "},
    { character: "CHEN BAILU", line: "Come along now, sit down, with my coat round your shoulders, and my scarf round your neck. "},
    { character: "CHEN BAILU", line: "And you put a leather robe over your feet, and you take this hot-water bag of mine; see? All done."}, 
      { character: "CHEN BAILU", line: " I like you so much, you're just like my father. Oh, my poor old Daddy! You suffered here, really!" },
    { character: "PAN YUETING", line: "Bailu, don't call me old Daddy." },
    { character: "CHEN BAILU", line: "I like calling you old Daddy. I want to call you old Daddy." },
    { character: "PAN YUETING", line: "I'm not old. Why do you call me an old daddy?" },
    { character: "CHEN BAILU", line: "I'm going to call you it, so there! My old daddy! My old Daddy!" },
    { character: "PAN YUETING", line: "Then call as you wish! I don't mind at all. I like it. I like it!" },
    { character: "CHEN BAILU", line: "Now sit still, Yueting. You're just like my little baby. I'll sing you a lullaby." },
    { character: "PAN YUETING", line: "Lullaby? No, I don't like that." },
    { character: "CHEN BAILU", line: "Then I'll read a novel to you. Listen." },
    { character: "PAN YUETING", line: "Sunrise. No, that's no good. The title's no good to start with." },
    { character: "CHEN BAILU", line: "Even if it's no good and you have to listen to it." },
    { character: "PAN YUETING", line: "No, I don't. I don't like listening to it." },
    { character: "CHEN BAILU", line: "No, you have to! Because I say it is." },
    { character: "PAN YUETING", line: "All right, all right, go ahead then." },
    { character: "CHEN BAILU", line: "'Then sun is risen, and the darkness is left behind.'" },
    { character: "PAN YUETING", line: "That doesn't make any sense." },
    { character: "CHEN BAILU", line: "'But the sun is not for us, for we shall be asleep.'" },
    { character: "PAN YUETING", line: "That doesn't make sense either, though the last sentence is quite something." },
    { character: "CHEN BAILU", line: "You're such a grinch. If you say another word, I'll hit you with---" },
    { character: "PAN YUETING", line: "What's that?" },
    // ... 继续添加更多对话 ...
    { character: "THE SHRIMP", line: "Miss! Miss!" },
    { character: "CHEN BAILU", line: "What?" },
    { character: "THE SHRIMP", line: "He...he's following me! He's awake!" },
    { character: "CHEN BAILU", line: "What? Who is that?" },
    { character: "THE SHRIMP", line: "Your dog's awake. He was trying to bite me." },
    { character: "CHEN BAILU", line: "You silly child. I thought they were coming in through the bedroom!" },
    { character: "PAN YUETING", line: "See how much trouble you got yourself into?" },
    { character: "THE SHRIMP", line: "There's someone at the door." },
    { character: "PAN YUETING", line: "Not them back again, I hope?" },
    { character: "CHEN BAILU", line: "Who is it?" },
    { character: "FANG DASHENG", line: "It's me, Zhujun." },
    { character: "CHEN BAILU", line: "Why aren't you in bed and why did you come back?" },
    { character: "FANG DASHENG", line: "I can't sleep in this place, it's too noisy. Fusheng told me just now that you adopted a girl." },
    { character: "CHEN BAILU", line: "A girl?" },
    { character: "FANG DASHENG", line: "Yes." },
    { character: "CHEN BAILU", line: "Oh, I see. She's here! Look, isn't she cute? This is my adopted daughter. We call here the shrimp." },
    { character: "FANG DASHENG", line: "The shrimp, eh?" },
    { character: "PAN YUETING", line: "Hey, hey! Bailu, don't stand there chatting away. Who is this gentleman." },
    { character: "CHEN BAILU", line: "You don't know him? Let me introduce you. This is my cousin." },
    { character: "PAN YUETING", line: "Your cousin?" },
    { character: "FANG DASHENG", line: "Zhujun? Why is there another man at this---" },
    { character: "CHEN BAILU", line: "Don't you know him? This is my Daddy." },
    { character: "PAN YUETING", line: "Yes, that's right! Daddy!" },
    { character: "FANG DASHENG", line: "Daddy?" },
    { character: "PAN YUETING", line: "What a happy family! " },
    // ... 继续添加更多对话 ...
    { character: "", line: "End of Act 1" }

  ];

  // Function to go to the next slide
  const nextSlide = useCallback(() => {
    setCurrentSlide((prevSlide) => (prevSlide + 1) % slides.length);
  }, [slides.length]);

  // Function to go to the previous slide
  const prevSlide = useCallback(() => {
    setCurrentSlide((prevSlide) => (prevSlide - 1 + slides.length) % slides.length);
  }, [slides.length]);

  useEffect(() => {
    const handleKeyDown = (event) => {
      if (event.key === 'ArrowRight') {
        nextSlide(); // Right arrow key pressed
      } else if (event.key === 'ArrowLeft') {
        prevSlide(); // Left arrow key pressed
      }
    };

    window.addEventListener('keydown', handleKeyDown); // Add event listener for keydown

    return () => {
      window.removeEventListener('keydown', handleKeyDown); // Clean up event listener on unmount
    };
  }, [nextSlide, prevSlide]);

  return (
    <div className="relative">
      <Slide {...slides[currentSlide]} />
      <button
        className="absolute top-3/4 left-4 bg-white text-black p-2 rounded"
        onClick={prevSlide}
      >
        Previous
      </button>

      <button
        className="absolute top-3/4 right-4 bg-white text-black p-2 rounded"
        onClick={nextSlide}
      >
        Next
      </button>
      <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 text-white">
        {currentSlide + 1} / {slides.length}
      </div>
    </div>
  );
};

export default Slideshow;

