import React, { useState , useEffect, useCallback} from 'react';
import './Slideshow.css'; // Optional: Create a separate CSS file for styles

// Slide Component
const Slide = ({ character, line, bgColor = 'bg-black', textColor = 'text-white' }) => (
  <div className={`flex items-center justify-center w-full h-screen ${bgColor} ${textColor} p-8`}>
    <div className="text-center max-w-4xl">
      <h1 className="text-4xl font-bold mb-4">{character}</h1>
      <p className="text-2xl italic">"{line}"</p>
    </div>
  </div>
);

// Slideshow Component
const Slideshow2 = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const slides = [
    {character:"Wang Fusheng",line:" Bah! Bah! Bahhhhh! Hai-ei-hai! Nothing but freaking ‘Hai-ei-hai’! By the time the building’s finished, we’ll all be driven to madness. "},
{character:"Wang Fusheng",line:" Listen! Listen to this! Still at it! When I can only in daytime snatch forty winks, these lot of good-for-nothings have to bawl on and on all day long! "}, 
{character:"Wang Fusheng",line:" Now that it’s getting all dark, these swine still keep on bawling and ramming, just won’t get fed up with this stuff! Born prole! Eat your expired junk! "}, 
{character:"Wang Fusheng",line:" Yuck! My son would starve to death than do such lowly work! Bah!  "},
{character:"Wang Fusheng",line:" Come on, then! Sing! Just go on with your hai-ei-hai! Just sing out loud! Now that I’m stuck with you! I’ll listen; you’ll sing; let’s see who in hell first gives in! See who gives in first!"},
{character:"Wang Fusheng",line:" Oh, Mr. Fang. You up already?"},
{character:"Fang Dasheng",line:" Why, of course—it is getting dark."},
{character:"Wang Fusheng",line:" It’s no wonder you’re up! No chance of sleeping with these bastard worthy to be butchered --"},
{character:"Fang Dasheng",line:" Hush! Listen!"},
{character:"Wang Fusheng",line:" Don’t you worry. I’ not afraid of them! Haven’t slept whole night, counting on daytime only for sleeping, but they won’t shut up, brawling all day. These paupers just won’t starve --"},
{character:"Fang Dasheng",line:" Listen, listen to their singing, talk not."},
{character:"Wang Fusheng",line:" Oh, you’re asking me to harken!"},
{character:"Fang Dasehng",line:" Right. "},
{character:"Fang Dasheng",line:" What beautiful singing!"},
{character:"Wang Fusheng",line:" Beautiful?"},
{character:"Fang Dasheng",line:" How cheerful they are! Just look at them, faces streaming with sweat, yet singing in high spirits!"},
{character:"Wang Fusheng",line:" Just born to slave in poverty. Or else you think they would spend their lives pile-driving and laboring, just to put up buildings for others to live in?"},
{character:"Fang Dasheng",line:" Who’s been building this?"},
{character:"Wang Fusheng",line:" Whoever is rich. It’s being built by the Da Feng Bank, by Mr. Pan, and perhaps Mrs. Gu in there is also in for it, too. "}, 
{character:"Wang Fusheng",line:"You see, they’re loaded, so they put up high-rise buildings to do with their money. The more they own, the more they make!"},
{character:"Fang Dasheng",line:" Mrs.Gu? You mean that old hag, face plastered in paint and powder?"},
{character:"Wang Fusheng",line:" Yes, exactly! Mutton dressed up like lamb, aging without knowing, but she’s rich! You see, that’s why everybody tells her how young and beautiful she is!"},
{character:"Wang Fusheng",line:"  Even Mr. Pan praises her up. You saw Mr. Pan went in there with Miss Chen and Mrs. Gu to play mahjong? I tell you, Mr. Gu’s rolling it!"},
{character:"Fang Dasheng",line:" But I have been out quite a while since that. They’re still in that room playing mahjong? Not gone yet?"},
{character:"Wang Fusheng",line:" Gone? Where to? It’s getting dark and a lot more people are coming, so they won’t be leaving."},
{character:"Fang Dasheng",line:" This place is really depressing. Even the room is dark as such."},
{character:"Wang Fusheng",line:" Tell me about it. Except the morning, this place wouldn’t get sunshine whole day. How come it’s not dark as such?"},
{character:"Fang Dasheng",line:" No sun, that’s it, sunshine does not often reach this place."},
{character:"Wang Fusheng",line:" Right, right, that’s it! But what’s the point of the sun? Gotta sleep in the day anyway, moving not until it’s getting dark."}, 
{character:"Wang Fusheng",line:" Lying there like a dead body in daytime, only to run here and there in the evening. We’re imps, so we don’t need sunshine."},
{character:"Fang Dasheng",line:" True, we don’t own the sun. To whom does the sun belong, then?"},
{character:"Wang Fusheng",line:" Who? Who cares?"},
{character:"Fang Dasheng",line:" Right, right, that’s it anyway, isn’t it?"},
{character:"Fang Dasheng",line:" Someone’s knocking."},
{character:"Wang Fusheng",line:" Who?"},
{character:"Fang Dasheng",line:" Wait a minute. I don’t want to meet these people, I’d go into that room."},
{character:"Wang Fusheng",line:" So it’s you here again! What are you doing here?"},
{character:"Huang Xingsan",line:" Sorry! I’m-I’m utterly sorry! I-I must have come to the wrong door."},
{character:"Wang Fusheng",line:" Come here! Come back! Where do you think you’re going?"},
{character:"Huang Xingsan",line:" Sir, I-I didn’t… You see, I came to a wrong door…"},
{character:"Wang Fusheng",line:" Wrong door or not, you must come back. Now, this isn’t a door you can randomly walk in and exit."},
{character:"Huang Xingsan",line:" But, but sir, I have made a mistake indeed, and, and I have apologized."},
{character:"Wang Fusheng",line:" Don’t you know there are all kinds of people in the hotel? Why didn’t you knock but barged straight in?"},
{character:"Huang Xingsan",line:" I, I did knock, sir-"},
{character:"Wang Fusheng",line:" Then how come I didn’t hear you?"},
{character:"Huang Xingsan",line:" Sir, how can I help it if you didn’t hear me? How about, pardon me, I knock on the door several times more?"},
{character:"Wang Fusheng",line:" You bastard! Who do you want anyway?"},
{character:"Huang Xingsan",line:" I-I’ve come to see Mr. Li."},
{character:"Wang Fusheng",line:" There are dozens of Mr. Li’s; who knows which one you want?"},
{character:"Huang Xingsan",line:" No, no, I mean Mr. Li in number fifty-two."},
{character:"Wang Fusheng",line:" This is room number fifty-two."},
{character:"Huang Xingsan",line:" Then, then I was right after all. I am looking for Mr. Li Shiqing "},
{character:"Wang Fusheng",line:" Not here."},
{character:"Huang Xingsan",line:" If Mr. Pan the bank manager isn’t busy, I’d like to see him instead. Would you mind telling him, sir?"},
{character:"Wang Fusheng",line:" Mr. Pan? Well, there is a Mr. Pan, but, you? You’d like to see Mr. Pan?"},
{character:"Huang Xingsan",line:" I, I’m a clerk at the Da Feng Bank."},
{character:"Wang Fusheng",line:" A clerk? Even a mention of your illustrious ancestors won’t cut any ice with men like Mr. Pan. He only drops for a social call to have fun and he’s never seeing visitors here."},
{character:"Huang Xingsan",line:" But, sir, please will you just go and ask him if he will see me!"},
{character:"Wang Fusheng",line:" Not here! Telling you, Mr. Pan’s not here! Now be off out of it! Don’t make a nuisance of yourself! You came here a complete stranger, butting in here trying to see people. Who can tell what you’re up to?"},
{character:"Huang Xingsan",line:" But, sir, I’m-I’m a clerk at the Da Feng Bank, and I’m Huang--"},
{character:"Wang Fusheng",line:" Do you know me or not?"},
{character:"Huang Xingsan",line:" I-I dare not say I do."},
{character:"Wang Fusheng",line:" Then quickly ‘march’! Go on, out!"},
{character:"Huang Xingsan",line:" But, sir I’m Huang-"},
{character:"Wang Fusheng",line:" Out! Out! Get out! Stop making a scene here! If you come here again I’ll--"},
{character:"Huang Xingsan",line:" Sir, I’m Huang, my name is Huang Xingsan, I used to be--"},
{character:"Wang Fusheng",line:" I know, you used to be a clerk, your name is , you’re looking for Mr. Li and Mr. Pan and everyone from the Da Feng Bank. "},
{character:"Wang Fusheng",line:" You’re going around everywhere pretending to be something you are not, trying to find a job. You think I don’t know nothing? Think I don’t know you?"},
{character:"Huang Xingsan",line:" Sir, you know me! That’s better still."},
{character:"Wang Fusheng",line:" I have seen you three times here at the hotel, but you still don’t recognize me at all. "},
{character:"Wang Fusheng",line:" You don’t think you’re going to find a job with a memory like that, you cuckold? Now clear off out of it, damn you!"},
{character:"Huang Xingsan",line:" Why should you call me that? I-I know I’m poor, but you can’t call me a cuckold, because I’m not, I’m telling you, I’m not. You, why are you--"},
{character:"Wang Fusheng",line:" You’d better ask your wife about that, how should I know? "},
{character:"Wang Fusheng", line:"All right, all right then, you’re not a cuckold, your son’s a cuckold’s brat, how’s that?"},
{character:"Huang Xingsan",line:" You—you, I’ll--"},
{character:"Wang Fusheng",line:" You’ll what? If you dare spit a word or lift a finger, I’ll beat you to death!"},
{character:"Huang Xingsan",line:" Let—me—go! Let—me—go!"},
{character:"Wang Fusheng",line:" Hello, who is it? Who is it? How’s it your business who I am?... I said who is it? Who do you want? How’s it your business who I am?... Who is it? Who is it you said? I’m not somewhere!... Swear at me?..."},
{character:"Wang Fusheng",line:" How could you call me a cuckold? Same to you! ....What? You’re Jin… Ah! Oh, you, sir, you are Mr. Jin! Yes… yes… yes…This is room fifty-two… Pardon me, please don’t hurry; I really couldn’t see who it was, "},
{character:"Wang Fusheng",line:"I didn’t know it was you, sir. Call it what you like, sir! Yes, yes, I deserve every word of it! It’s just as you say, sir, just as you say!"},
{character:"Pan Yueting",line:" Who? Who’s ringing? Is it Mr. Li Shiqing ?"},
{character:"Wang Fusheng",line:" …No, I dare not…No, I wouldn’t dare do that again… Yes… Right, right, I am Fusheng! I’m that cuckold Fusheng…"}, 
{character:"Wang Fusheng",line:"now please don’t get angry; don’t fall ill for it, sir…I am bastard, …sure…sure, you want Mr. Pan? Would you hold on for a second, he is coming. (To Pan) For you, sir. Yes, yes, you’re right… yes, yes, yes, I’m a cuckold, not of human parentage."},
{character:"Pan Yueting",line:" You idiot! Who is it！"},
{character:"Wang Fusheng",line:" Who? Who?... Oh, it’s Mr.Jin, Mr.Jin."},
{character:"Pan Yueting",line:" Hasn’t Li Shiqing , Mr. Li come yet?"},
{character:"Wang Fusheng",line:" Not yet, Mr. Li’s not here yet."},
{character:"Pan Yueting",line:" Then go in and ask Mrs. Li  what time her husband said he’d be here."},
{character:"Wang Fusheng",line:" Sure, sir."},
{character:"Pan Yueting",line:" Is it Mr. Jin?... I’m Yueting… Yes, yes, there won’t be any trouble about your deposit. If you’ll just hold on for three days, and then come for it, and I’ll definitely let you have it… "}, 
{character:"Pan Yueting",line:"Yes, yes, the Da Feng Bank’s doing fairly well, and I’ve made quite a bit on my government bonds—Salt-tax and Disbandment, so don’t you worry, three days and your deposit in the Da Feng will definitely be repaid… "}, 
{character:"Pan Yueting",line:"What?... Nonsense! ...There’s nothing like that, there’s no depositors rushing to withdraw their money!... Who said that?..."}, 
{character:"Pan Yueting",line:" Um, er, all rumors, don’t you believe in them. You see, Mr.Jin, isn’t the bank building Da Feng block beside the hotel?... Why? … "}, 
{character:"Pan Yueting",line:"Of course, we’re keeping one’s money on the move when there’s a flourishing the market. Now don’t worry! No question about the bank’s reserve… Three days, for old time’s sake, you just hold on for three days, and you’ll get fully repaid… Oh, yes, Mr. Jin… "},
{character:"Pan Yueting",line:"any special news about the government bonds? Ah, yes…so I have heard, the market’s looking up. Right, looking up… but, sir, haven’t you bought a few?... Yes, yes."},
{character:"Wang Fusheng",line:" Mrs. Li  says Mr. Li will be here very soon. Mr. Pan’s here, Mrs. Gu"},
{character:"Mrs. Gu",line:" No, I’m literally worn out, I couldn’t possibly play another round anyway. Mr. Pan! Why, what are you doing in here all on your own?"},
{character:"Pan Yueting",line:" ‘Mrs. Gu’."},
{character:"Mrs. Gu",line:" No, no, Mr. Wang, I’m tired. No, Bailu, my heart, it’s my heart, if I play anymore, my old trouble will be back again. Let me have a rest, my heart is aching."},
{character:"Pan Yueting",line:" …Yes, all right, good-bye then, good-bye. Well, now, Mrs. Gu"},
{character:"Mrs. Gu",line:" You, Mr. Pan, you are really a naughty person, leaving the game to come here all alone to talk to someone on the phone!"}, 
{character:"Mrs. Gu",line:"  You’d better be careful, I’m telling you, Bailu’s playing mahjong with friends just in there! You, Mr. Pan, who are you secretly running after now? It’ll be safe with me, so tell me, who’s that woman? "}, 
{character:"Mrs. Gu",line:" Why did she find you here and ring you up?"}, 
{character:"Mrs. Gu",line:"  You men, I know, are good in every aspect, clever at making money and spending money at the same time, but none of you understand a thing about love, the greatness of love, and how great love is—"},
{character:"Pan Yueting",line:" Mrs. Gu is the most sentimental woman in the world!"},
{character:"Mrs. Gu",line:" And that’s why I’m most tragic, most helpless, most passionate, most helpless."},
{character:"Pan Yueting",line:" Why, Mrs. Gu, why do you suddenly stop playing? Helplessness will be gone when you have a game of mahjong."},
{character:"Mrs. Gu",line:" Oh, yes, would you mind pouring a glass of water for me, Mr. Pan? I have to take medicine."},
{character:"Pan Yueting",line:" What’s the matter? You want other pills?"},
{character:"Mrs. Gu",line:" Don’t ask me yet. Quickly, give me the water, after I have finished with the medicine."},
{character:"Pan Yueting",line:" Are you alright? Bailu has got all kinds of medicine here."},
{character:"Mrs. Gu",line:" A bit better!"},
{character:"Pan Yueting",line:" How about taking some of Bailu’s sleeping tablets and take a nap?"},
{character:"Mrs. Gu",line:" No! There’s no need! I’ve got pain in my heart! I stopped playing just now only because I suddenly began thinking about  Hu Si  the ungrateful creature, and that’s the reason why I’ve pain in my heart again. You feel it if you don’t believe me!"},
{character:"Pan Yueting",line:" I believe you. I believe you."},
{character:"Mrs. Gu",line:" Come feel it!"},
{character:"Pan Yueting",line:" Yes, yes. Feels alright to me, all right."},
{character:"Mrs. Gu",line:" What do you mean? Alright? I’m dying and my heart is thumping so hard it’s literally bursting. "},
{character:"Mrs. Gu",line:"I’ve been to one doctor after another, all claiming that there’s no problem with me, but I didn’t believe it! Then I spent two hundred on a French doctor, M. Ledoux, to get examined, and he immediately said I have heart trouble. "},
{character:"Mrs. Gu",line:"It was no wonder that my heart often pained me, when I’ve got heart trouble all the time. Feel it again if you don’t believe me! Listen, it’s keeps pounding away."},
{character:"Pan Yueting",line:" All right, yes, sure, it’s pounding away."},
{character:"Chen Bailu",line:" Oh! Yueting, you here too?"},
{character:"Mrs. Gu",line:" Look! Mr. Pan’s giving me a medical treatment!"},
{character:"Chen Bailu",line:" Is it your heart trouble again? Mr. Liu, I’ll let you mahjong though you have got such a big hand; Mrs."}, 
{character:"Chen Bailu",line:" Li, pardon me for running off like this, and if you want anything, just ring for it and feel at home. I have to stay with my new friend."},
{character:"Pan Yueting",line:" New friend!"},
{character:"Mrs. Gu",line:" Which new friend? From where?"},
{character:"Chen Bailu",line:" I thought Da Sheng was here."},
{character:"Pan Yueting",line:" You say your cousin Mr. Fang?"},
{character:"Chen Bailu",line:" Yes, I saw him here just now."},
{character:"Mrs. Gu",line:" You don’t mean that gentleman who starts frowning upon meeting people? Don’t you ever invite him here again! He gives me the creeps."},
{character:"Chen Bailu",line:" But he lives here."},
{character:"Mrs. Gu",line:" Right here? "},
{character:"Chen Bailu",line:" Yes—Dasheng! Dasheng!"},
{character:"Fang Dasheng",line:" Oh, it’s you! What did you want me for?"},
{character:"Chen Bialu", line:"What are you up to? Why not come out here and mix with the others?"},
{character:"Fang Dasheng",line:" I’ve been having a chat with the Shrimp, your adopted daughter. She’s a sweet child."},
{character:"Chen Bailu",line:" And now how about coming out here for a chat with us. Come and join us, don’t be so unkindly."},
{character:"Fang Dasheng",line:" Oh, here’s your father, and seems your mother is here too. No, no, I’d rather talk with your adopted daughter."},
{character:"Chen Bailu",line:" There’s just no way getting him to do anything."},
{character:"Pan Yueting",line:" You know  Mrs. Gu ,Hu Si again hasn’t been in to the bank for work the last few days."},
{character:"Mrs. Gu",line:" I’ve talked into this issue with him and he went off in a huff. Mr. Pan, please don’t take that too seriously, he—he’s just--"},
{character:"Pan Yueting",line:" All right, let’s talk no more about him. Look, they’ve already started working on the bank’s new building. "}, 
{character:"Pan Yueting",line:" Once they’ve got footings in they’ll finish building straight away."},
 {character:"Pan Yueting",line:"In a good position like this, we’ve only got to let it and we can guarantee a fifteen per cent interest at least. If the market improves slightly, we’ll make more than twenty or even thirty percent."},
{character:"Mrs. Gu",line:" Listen to the wonderful schemes Mr. Pan’s got, Bailu. What is it that you were telling me, Mr. Pan? When the market is something-or-other, the economy is something else, you—what is it you said one should do?"},
{character:"Pan Yueting",line:" I said, when the market is critical and the economy unstable, one should invest in estates."},
{character:"Mrs. Gu",line:" That’s it; you see, Bailu, if now I spend not on putting up building, wouldn’t my market be unstable? "}, 
{character:"Mrs. Gu",line:" So, Mr. Pan, you’re quite right when you had the idea of putting up this big building."}, 
{character:"Mrs. Gu",line:"Twenty percent interest, two to three thousand a month, very handy to help out with one’s pocket money."},
{character:"Wang Fusheng",line:" Mr. Pan, Mr. Zhang from the newspaper office is here."},
{character:"Chen Bailu",line:" What’s he want with you all of a sudden."},
{character:"Pan Yueting",line:" I asked him over so that I could ask him what’s been happening these last few days. "},
{character:"Wang Fusheng",line:" Shall I ask him to come in?"},
{character:"Pan Yueting",line:" No, you take him to room number thirty-four. Don’t take him here."},
{character:"Wang Fusheng",line:" Ms. Chen, Mrs. Dong is here, and Ms. Liu too."},
{character:"Chen Bailu",line:" Take them all over to the other side, and tell them I’ll be there soon."},
{character:"Wang Fusheng",line:" Yes, Miss."},
{character:"Pan Yueting",line:" Well then, Mrs. Gu, that’s settled, I’ll have your bank deposit transferred."},
{character:"Mrs. Gu",line:" I leave it all to you. Nothing will go wrong in your hands."},
{character:"Pan Yueting",line:" Good, I’ll discuss it with you later. "},
{character:"Chen Bailu",line:" Yueting, just a moment. Still remember what I told you?"},
{character:"Pan Yueting",line:" What?"},
{character:"Chen Bailu",line:" That little shrimp, I want to keep her as my adopted daughter. Would you make it all right with Mr. Jin and put us in the clear."},
{character:"Pan Yueting",line:" Sure, don’t worry, I’ll see to it."},
{character:"Chen Bailu",line:" Thank you."},
{character:"Pan Yueting",line:" No, no thanks. I’d be satisfied if you call me ‘daddy’ less frequently."},
{character:"Mrs. Gu",line:" Bailu, I do admire you! I really don’t know how to do justice to you. You’re a masterpiece—charming, beautiful, romantic, voluptuous. "}, 
{character:"Mrs. Gu",line:"Alone in a place like this, yet with friends everywhere. Take Mr. Pan, for example, he’s in line with nobody, but he says he only supports you. "}, 
{character:"Mrs. Gu",line:"Mr. Pan’s a good man, a most competent man; to quote a modern phrase, he’s a ‘unique unprecedented first-class type’. "},
{character:"Mrs. Gu",line:"Is there anyone to beat him, whether it’s real estate, stock or government bonds?"},
{character:"Mrs. Gu",line:" That’s why I’ve put my money in his hands for him to invest for me. "},
{character:"Mrs. Gu",line:"You see, this is the one you’ve fallen for at the first sight, you’ve hooked him, when you say yes he dare not say no, so I’d say you’re the woman with the most wonderful prospects in China."},
{character:"Chen Bailu",line:"I didn’t hook him, it’s he on his free will that comes to me, what can I do about it? "},
{character:"Mrs. Gu",line:" Anyway, it’s a case of ‘a turtle staring at a green bean…’ Oh, no, sounds spooky…"}, 
{character:"Mrs. Gu",line:"You don’t know, I’ve made in the past half year quite a few friends of new school, so I always don’t know what to say in the first place with all those new terms in my mind… "}, 
{character:"Mrs. Gu",line:"What I was saying just now is that, Mr. Pan is like Chevalier from The Love Parade, and you the MacDonald—you two literally rival each other, and no other pair can rival you two. "},
{character:"Chen Bailu",line:" You’re acquiring the gift of the gab these days. I always find it hard to think of something to say when I meet you, for you’ve exhausted all wonderful words."},
{character:"Mrs. Gu",line:" You mean that?"},
{character:"Chen Bailu",line:" I mean that."},
{character:"Mrs. Gu",line:" I feel the same myself. Ever since my husband passed away, I seem to have had my tongue unbound. "}, 
{character:"Mrs. Gu",line:"Suddenly I’ve become cleverer and I can put my tongue to anything. But what’s the use of having a clever tongue? One still cannot hold a man’s heart with it. Now, Bailu, I’m realizing that men absolutely have no conscience. "},
{character:"Mrs. Gu",line:"However well you treat him, it’s all wasted effort."},
{character:"Chen Bailu",line:" Why, what’s Hu Si  been up to now?"},
{character:"Mrs. Gu",line:" Heaven knows what he’s doing! I haven’t seen a thing of him for the past couple of days. "}, 
{character:"Mrs. Gu",line:"I told him to come, and I’ve phoned him, written to him even gone to see him myself, but he’s never home. What can you think of a man like that after all the money I have spent on him and my lavish affection on him! "}, 
{character:"Mrs. Gu",line:"And now look, once he gets pissed off, he’d ignore me for days on end."},
{character:"Chen Bailu",line:" In that case you’ve every right to ignore him in turn, and save yourself a lot of bother."},
{character:"Mrs. Gu",line:" But… no, that’s not the answer. I think that however revolutionary a woman might be, she must still have some regard for ‘submission and propriety’. So no matter how badly Hu Si treats me, I shall always have considerable affection for him."},
{character:"Chen Bailu",line:" Oh my dear! Congratulations, congrats! "},
{character:"Mrs. Gu",line:" Now what?"},
{character:"Chen Bailu",line:" Congrats on becoming more reasonable every day! Now fancy you’re embracing ‘submission and propriety’ when facing Hu Si !"},
{character:"Mrs. Gu",line:" What! You don’t think I’m a woman with no character or principles?"},
{character:"Chen Bailu",line:" But, my dear, you’ve got to ride in the bridal sedan-chair again and have a solemn and spectacular wedding with Hu Si if you are talking about ‘submission and propriety’ with him!"},
{character:"Mrs. Gu",line:" You mean that Hu Si and I should get married? Don’t you mention that! If he’s treating me like this even before we’re married, he’d treat me a lot worse afterwards—"}, 
{character:"Mrs. Gu",line:"I ‘d be no better than an old cast-off shoe! And this modern-style marriage is of no use:"}, 
{character:"Mrs. Gu",line:" if he changes his mind, he’s only got to go to a lawyer and abandon me. It’s no longer like when I married my late lamented, that no matter what he did I was still his wife!  "},
{character:"Mrs. Gu",line:" And a wife who’d been married in a bridal chair, too, so he had to behave himself and keep me and pay my bills as a lord and master should. You say divorce the wife he’d lawful wedded?"},
{character:"Mrs. Gu",line:" That’s absolutely daydreaming! No fear of that! But now… now…Bailu, you’re a clever girl, just think about it, what’s the point of getting married? What’s the point of it?"},
{character:"Chen Bailu",line:" There’s no point in it either way. But I always thought that to make a lover into one’s husband does seem a great pity."},
{character:"Mrs. Gu",line:" That’s just what I was talking about! You see, having a meal together, or going for a dance—everything goes quite well for the couple so long as they’re not married. But once, they get married, humph—"}, 
{character:"Mrs. Gu",line:"No, it can’t be done! Hu Si  can say whatever he likes about it; if he proposes to me I shall refuse. Besides, I’m afraid of him, that once we were married he’d show his true {character; and you know my eldest daughter—"}, 
{character:"Chen Bailu",line:" You mean the young lady that’s been to university?"},
{character:"Mrs. Gu",line:" That’s the one."},
{character:"Chen Bailu",line:" What about her?"},
{character:"Mrs. Gu",line:" You know I’m a most free-and-easy person, most unlike my daughter, just the opposite. She’s quite intellectual, a Christian, goes in for charities, quite gives herself airs. "}, 
{character:"Mrs. Gu",line:"But I’m not like that. Once I’d set my heart on Qiu, nothing else mattered to me; now that I’ve fallen for Hu Si I live only for him. Funny, isn’t it? My daughter’s like that when I’m like I am? Must be something to do with heredity, huh?"},
{character:"Chen Bailu",line:" But, my dear Mrs. Gu, what’s that got to do with your getting married?"},
{character:"Mrs. Gu",line:" Oh, right, I’ve almost forgotten when talking away. I tell you, my daughter’s dead against Hu Si —though of course I’m pretty clear that she’s afraid Hu Si  would spend all my money; and also, if I married him, you see, their ages would be… "}, 
{character:"Mrs. Gu",line:"well, um, there wouldn’t be much difference between their ages. Just imagine how difficult it would be to know what she should call him, and it would be rather embarrassing for me as a mother!"},
{character:"Chen Bailu",line:"  Well, Hu Si is treating you badly all the time, I don’t see any reason you should be so very attached to him."},
{character:"Mrs. Gu",line:" But that’s what love does to you! Of course, I do realize he’s lazy and won’t change till the day he dies, so I got Mr. "}, 
{character:"Mrs. Gu",line:"{Pan to find him a job after much coaxing and pleading. Mr. Pan said that the business was bad, but for my sake he dismissed fifteen people—no, about twenty people, no, fifteen or twenty? Anyway, ten people or so, to squeeze him in. But what does Hu Si  do?"},
{character:"Mrs. Gu",line:"  He either says that the salary is low or that the work does not interest him, and after going for a couple of days he now stopped going in regularly. "},
{character:"Mrs. Gu",line:"Lazy, good-for-nothing, helpless—ah, poor boy, he’s born this way! If I don’t take him under my wing, who will? Ah, love! I’ve never understood what the word really meant till now."},
{character:"Chen Bailu",line:" Oh, now you understand what love is, no wonder you’ve become so clever."},
{character:"Mrs. Gu",line:" I tell you, love is when you willing give him money for him to spend and don’t mind how he squanders it—that’s what love is! Love!"},
{character:"Chen Bailu",line:" That explains why I’m always told that love has its price. Now I’ve finally come to understand what it means."},
{character:"Mrs. Gu",line:" Yes, so I’d like to ‘pay some more price’ for Hu Si I’d like to get Mr. Pan to find him a job with a film company. "}, 
{character:"Mrs. Gu",line:"Bailu, we’re good friends, like sibling sisters, couldn’t you have a word with Mr. Pan for me? I really have no face to bother him again myself."},
{character:"Chen Bailu",line:" Oh, you mean you want him to be a film-star?"},
{character:"Mrs. Gu",line:" Yes, and what a hit he’d be! Don’t you see, he’s every inch a film-star: Physique, features, nose, eyes."},
{character:"Chen Bailu",line:" But, aren’t you afraid of having other women run after him?"},
{character:"Mrs. Gu",line:" No, that’s the point that I have complete faith in him. He’s incapable in all other aspects but for devotion to me—he follows me about like a little dog. "}, 
{character:"Mrs. Gu",line:"Er, em, of course he’s not seeing me these days lately, but you can’t blame him for that. "}, 
{character:"Mrs. Gu",line:"He asked me for three hundred, but I wouldn’t let him have it; "},
{character:"Mrs. Gu",line:"he wanted me to buy a new car, a Chevrolet, but as I couldn’t put my hand on the money, I said no. Then he proposed to me—I’m telling you, it was the twelfth time he did so—"},
{character:"Mrs. Gu",line:"I turned down him again, so it’s no wonder he’s annoyed."},
{character:"Chen Bailu",line:" So just think about it, find him a good position to put him in a good humor again."},
{character:"Mrs. Gu",line:" I promised him this time, that as long as he’ll become a film-star, I’ll find some way to marry him. Let me tell you all about it; "}, 
{character:"Mrs. Gu",line:"I’ve thought about it all, that we’re sure to get some really big pictures in the papers, of me, of  Hu Si , and one of both of us together, and every day the papers will report the news of our honeymoon. And also—"},
{character:"Chen Bailu",line:" Congrats, congratulations! Now you think it interesting to get married; I definitely will come to your wedding ceremony and enjoy a feast. But what about your university-trained daughter?  What are you going to do about her?"},
{character:"Mrs. Gu",line:" Oh, once Hu Si  become a film-star everything will be different. I’ll getHu Si , as a film-star, to go along to her charity fetes and so on and sing a romantic song or two, dance the hula, and she’ll be delighted, you see if she isn’t!"},
{character:"Chen Bailu",line:" My dear, I’ll surely do for you. You’re so very clever, and you think about everything. I promise you, that I’ll definitely see Mr. Pan about it, and tomorrow get him a job in the film company, how about that?"},
{character:"Mrs. Gu",line:" Thanks! Thank you! There, didn’t I say? You are a masterpiece, no woman, before or after, can rival you, and there’s no doubt with that."},
{character:"Wang Fusheng",line:" Oh, I didn’t realize you were here, Mrs. Gu"},
{character:"Mrs. Gu",line:" What do you want?"},
{character:"Wang Fusheng",line:" I’ve come to find Miss Chen."},
{character:"Chen Bailu",line:" For those bills in your hands?"},
{character:"Wang Fusheng",line:" Yes, Miss. Mr. Pan’s paid the bills that were due yesterday for you, and he told me to bring them to you."},
{character:"Chen Bailu",line:" Just burn them for me."},
{character:"Wang Fusheng",line:" Sure, sure, but here, here are some more—"},
{character:"Chen Bailu",line:" More?"},
{character:"Wang Fusheng",line:" I’ll tell you what they are if you—"},
{character:"Chen Bailu",line:" Can’t you see I’ve got a visitor here?"},
{character:"Wang Fusheng",line:" Sorry, miss."},
{character:"Georgy Zhang ",line:"Bonjour! Bonjour! I’d guessed you are here in this room! Bonjour! Bonjour!"},
{character:"Mrs. Gu",line:" Oh! Here comes our Doctor Zhang!"},
{character:"Georgy Zhang ",line:"Mademoiselle Gu! You really do look prettier every day!"},
{character:"Mrs. Gu",line:" Is that so, doctor?"},
{character:"Georgy Zhang ",line:"Tiens! My little Lulu, this dress of yours is—"},
{character:"Chen Bailu",line:" Ravissante!"},
{character:"Georgy Zhang ",line:"That’s exactly the word! You’re brilliant, you always know what I’m going to say. By the way, er, garcon!"},
{character:"Wang Fusheng",line:" Wee, m’shoor? "},
{character:"Georgy Zhang ",line:"Tell them in the room that I won’t be joining them for mahjong."},
{character:"Wang Fusheng",line:" Wee, m’shoor!"},
{character:"Chen Bailu",line:" Don’t keep frisking around like this. Sit down, won’t you?"},
{character:"Georgy Zhang ",line:"Bon, s’il vous plait, je vous prie, excusez moi, ma cherie."},
{character:"Mrs. Gu",line:" Hey you two, could you stop talking that foreign gibberish?"},
{character:"Georgy Zhang ",line:"Oh, je m’excuse, pardonnez-moi ! I’m terribly sorry, but you see, speaking foreign language is always more convenient, I’ve really got out of the habit of speaking Chinese."}, 
{character:"Georgy Zhang ",line:" Now it’s getting better, I’ve finally remembered a bit. When I just got back, I could hardly speak a single complete sentence in Chinese. Just see how mighty foreign stuff can be."},
{character:"Mrs. Gu",line:" Doctor, how very lucky you are—you’ve been to foreign countries. Ah, however mighty foreign language might be, I could not forget Chinese for my whole life! Pity me!"},
{character:"Chen Bailu",line:" Georgy, why are you all dressed up like this today?"},
{character:"Georgy Zhang ",line:"You have no idea what a lot of things one gets caught for working in a government office. "}, 
{character:"Georgy Zhang ",line:"One day it’s some ceremony or other, the next a wedding one has to attend. Liu, the head of our department in the ministry, was married today, and I was his best man. But suddenly thought of you without waiting to change first. "}, 
{character:"Georgy Zhang ",line:"Oh, yes, I’ve bought you these flowers, to express my wish that you’ll always be as beautiful as you are today, and also a token of my apologies. Last night, I came to your suite just to—"},
{character:"Mrs. Gu",line:" What happened last night?"},
{character:"Chen Bailu",line:" That’s all right."},
{character:"Georgy Zhang ",line:"All right, you say? That’s great! I always knew you were generous."},
{character:"Mrs. Gu",line:" Doctor, haven’t you been around with Hu Si  the last few days, have you?"},
{character:"Georgy Zhang ",line:"Hu Si? I saw him the other day at the club wandering about with a—"},
{character:"Mrs. Gu",line:" A what?"},
{character:"Georgy Zhang ",line:"Wandering about with a dog."},
{character:"Mrs. Gu",line:" The callous creature without conscience. He’d rather hang around with a dog than me."},
{character:"Georgy Zhang ",line:"Why, have you two fallen out again? Then what’s he doing sitting outside in a car?"},
{character:"Mrs. Gu",line:" What? He’s outside? At the gate?"},
{character:"Georgy Zhang ",line:"That’s odd! Didn’t you know? "},
{character:"Mrs. Gu",line:" Doctor, you really don’t act like a well-educated man. Why didn’t you tell me before?"},
{character:"Georgy Zhang ",line:"I don’t see education is any guarantee of being able to divine your wish to see Hu Si, isn’t it?"},
{character:"Mrs. Gu",line:" Well, I can’t stop here arguing with you, I must be off. Oh, and Bailu, you’ve got to remember what I’ve asked you to do for me. When you see Mr. Pan, don’t forget to put in a word for me."},
{character:"Chen Bailu",line:" All right."},
{character:"Mrs. Gu",line:" Doctor Zhang, Au’voir! Au—’voir !"},
{character:"Georgy Zhang ",line:"Whew! Finally got rid of the old hag. Bailu, I must tell you the good news. "},
{character:"Chen Bailu",line:" What good news? Your wife gave birth to another son for you?"},
{character:"Georgy Zhang ",line:"Pah! You’re impossible. "},
{character:"Chen Bailu",line:" Then you must have been promoted."},
{character:"Georgy Zhang ",line:"It amounts to much the same thing as promotion. I’m telling you, I got a divorce from my wife yesterday afternoon, a proper divorce!"},
{character:"Chen Bailu",line:" A divorce? Why, he’s given you three children, and now you’re leaving them?"}, 
{character:"Chen Bailu",line:" She’s been raising the children to free you of the worries and be focused on your doctoral degree, how could you divorce her as soon as you get back?"},
{character:"Georgy Zhang ",line:"What do you mean? I’ve paid her; I’ve got money and I’ve made her proper settlement. I didn’t expect that you’re acting like not knowing the ways of the world."},
{character:"Chen Bailu",line:" True, so that’s why I need to learn from you now what ‘the ways of the world’ means."},
{character:"Georgy Zhang ",line:"No, Lulu, we’re not talking about her. Just forget about it. Now let me tell you my other piece of good news."},
{character:"Chen Bailu",line:" Georgy! So much good news you’ve got today!"},
{character:"Georgy Zhang ",line:"Lulu, do you know why I came here last night?"},
{character:"Chen Bailu",line:" Don’t tell me you came to propose to me, too?"},
{character:"Georgy Zhang ",line:"Oh la la! Juste ciel! You must be God himself, the way you can guess whatever is going on in my mind! "},
{character:"Chen Bailu",line:" What? You—"},
{character:"Georgy Zhang ",line:"No, Lulu, you must pity on me, a man who has just divorced and has no one to love him. You’ve got to say yes."},
{character:"Chen Bailu",line:" You mean that when you came here and made that scene last night, sick all over my bed, you mean you’d come to propose to me?"},
{character:"Georgy Zhang ",line:"That was because I was drunk."},
{character:"Chen Bailu",line:" I’m well aware of that."},
{character:"Georgy Zhang ",line:"That was because I was so overjoyed! I, I just couldn’t get over the realization that I was going to be the happiest and luckiest man in the world, because I knew you’d definitely marry me."},
{character:"Chen Bailu",line:" How weird! Why should you men be so very confident about yourselves?"},
{character:"Georgy Zhang ",line:"Lulu, I’ve got a house in Guangdong Road, I’ve some shares in the Da Xing Mines, and I’ve several thousands in cash in the Da Feng Bank, and of course you know I’m still in the government service."}, 
{character:"Georgy Zhang ",line:"Later on, should my luck hold, there wouldn’t be the slightest difficulty in securing an income of three or four thousand dollars a month. In addition to all this, I didn’t do so badly when I was abroad: "}, 
{character:"Georgy Zhang ",line:"I’m a Ph. D., a B.Sc. in economics, and an M.A. in political science, and also—"},
{character:"Chen Bailu",line:" Dasheng, Dasheng, come out here."},
{character:"Fang Dasheng",line:" Oh, it’s you two. I’m sorry, I’ve probably heard it wrong."},
{character:"Chen Bailu",line:" No, I called you, just come here. Open the window, quickly."},
{character:"Georgy Zhang ",line:"What for?"},
{character:"Chen Bailu",line:" I want to breathe some fresh air. There’s an awful fug in here all of a sudden."},
{character:"Fang Dasheng",line:" Fug?"},
{character:"Chen Bailu",line:" Why, yes, can’t you smell it?"},
{character:"Fang Dasheng",line:" In the room. The kid is lovable; I really like her."},
{character:"Chen Bailu",line:" Take her away, will you?"},
{character:"Fang Dasheng",line:" Sure, why, I happen to want a little sister like this."},
{character:"Chen Bailu",line:" Then I’ll give her to you."},
{character:"Fang Dasheng",line:" Thank you! Then that’s settled."},
{character:"Georgy Zhang ",line:"I say, Bailu. You… you, aren’t you going to introduce me? Don’t be so impolite, you know."},
{character:"Chen Bailu",line:" Oh, haven’t you met?"},
{character:"Georgy Zhang ",line:"You face is familiar. Seems we have met before."},
{character:"Fang Dasheng",line:" But Mr. Zhang, I know you quite well. Your foreign name is Georgy Zhang, Chinese name Zhang Qiaozhi, and you’ve got a master or doctoral degree or something, and also, you’ve been chief in the government office for several terms—"},
{character:"Georgy Zhang ",line:"Why, of course, of course. We’ve met before, we’re old friends!"},
{character:"Chen Bailu",line:" Really? Where did you meet?"},
{character:"Georgy Zhang ",line:"Yes, we’re old friends. I remember now, five years ago it was, we came back together on the same boat from Europe. Ah, so many years it’s been, jolly glad to see you again. Sit down, do."},
{character:"Chen Bailu",line:" What’s the idea of all this?"},
{character:"Fang Dasheng",line:" There’s no telling what he’s after!"},
{character:"Li Shiqing ",line:" Good evening, Miss Chen! Doctor Zhang!"},
{character:"Georgy Zhang ",line:"Ah, you’ve come just right. Mr. Li, I’d like you to meet an old friend of mine."},
{character:"Li Shiqing ",line:" Sure, very pleased to."},
{character:"Georgy Zhang ",line:"This is Li Shiqing , Mr. Li, secretary at the Da Feng Bank, Mr. Pan’s right-hand man."},
{character:"Li Shiqing ",line:" Not at all, not at all. And this gentleman is—"},
{character:"Georgy Zhang ",line:"This is an old fellow-student of mine who came back from Europe with me, Mr.-- er, Mr. –"},
{character:"Fang Dasheng",line:" Fang."},
{character:"Georgy Zhang ",line:"Of course! What a terrible memory I’ve got, yes, Fang, Mr. Fang."},
{character:"Li Shiqing ",line:" Pleased to meet you."},
{character:"Chen Bailu",line:" Mr. Li, you’d better watch out. Mrs. Li’s looking for you, says she wants to see you about something."},
{character:"Li Shiqing ",line:" Is she? I don’t see her having time to speak to me. She’s playing mahjong at the moment."},
{character:"Chen Bailu",line:" Still? She told me long time ago she wasn’t playing any more. How’s she getting on, losing or winning?"},
{character:"Li Shiqing ",line:" My wife’s a poor player, so of course she’s losing. But she’s keeping her losses down, only three or four hundred dollars, nothing—"},
{character:"Chen Bailu",line:" Nothing to speak of."},
{character:"Li Shiqing ",line:" You’re a most clever one, Miss Chen, the way you can take the words out of one’s mouth. Really, though, it’s a pleasure even to lose when we come here to your place for mahjong."},
{character:"Chen Bailu",line:" Thanks for the compliment, though I really don’t deserve it."},
{character:"Georgy Zhang ",line:"You haven’t run into Mr. Pan, I suppose?"},
{character:"Li Shiqing ",line:" As a matter of fact, I came here hoping to find him."},
{character:"Chen Bailu",line:" He’s probably in room thirty-four. You can go ask Fusheng."},
{character:"Li Shiqing ",line:" Thank you, Miss Chen. In that case, please excuse me for leaving for a moment. Excuse me, Dr. Zhang, Mr. Fang."},
{character:"Li Shiqing ",line:" Mrs. Gu Mr. Hu."},
{character:"Mrs. Gu",line:" Help me get him in."},
{character:"Li Shiqing ",line:" What’s happening now?"},
{character:"Hu Si ",line:" Take no notice of her."},
{character:"Li Shiqing ",line:" You must excuse me, I have to see Mr. Pan. I’m sorry, excuse me."},
{character:"Mrs. Gu",line:" Now you’re to stay with me! I won’t have you looking at her! When I say you can’t look at her, you can’t! Do you hear me or not?"},
{character:"Hu Si ",line:" All right, all right, all right! I heard you. But look at what you’ve done! Good clothes ruined!"},
{character:"Mrs. Gu",line:" All this fuss!"},
{character:"Chen Bailu",line:" Now what’s all this about?"},
{character:"Hu Si ",line:" Nothing. What a way to go on!"},
{character:"Mrs. Gu",line:" We are having fun, aren’t we, quarrelling all day like this?"},
{character:"Chen Bailu",line:" You’re like a pair of children, making scenes like that in front of others."},
{character:"Mrs. Gu",line:" But we are a couple of children! Aren’t we? Now I ask you, why did you insist on looking at that woman? What’s so beautiful about her? Coarse, fat, common, uneducated—"},
{character:"Hu Si ",line:" Oh, forget it, why must you keep on about it? Didn’t I come in when you told me to? Oh, doctor, you’re early."},
{character:"Georgy Zhang ",line:"Oh, hey stranger, what have you been doing with yourself lately?"},
{character:"Hu Si ",line:" Nothing to speak of. Fooled around in the club, larked about with the girls round the dance-halls—simply nothing to speak of, nothing interesting!"},
{character:"Mrs. Gu",line:" Humph, some low hussy’s got her claws into you again, I suppose."},
{character:"Hu Si ",line:" There you go again! If you say so, so be it."},
{character:"Mrs. Gu",line:" I didn’t say for certain."},
{character:"Hu Si ",line:" That’s all right then, isn’t it?"},
{character:"Wang Fusheng",line:" Miss Chen, the refreshments are ready in room fifty-one. Would like to take a look at them first?"},
{character:"Chen Bailu",line:" All right, I’ll be straight along."},
{character:"Wang Fusheng",line:" Very good, Miss."},
{character:"Chen Bailu",line:"Hu Si have you met my new visitor? Mr. Fang, newly arrived, a cousin of mine. This is Hu Si the most handsome boy in China."},
{character:"Mrs. Gu",line:" Don’t praise him up so, he’ll only go making my life a misery again."},
{character:"Chen Bailu",line:" Well, you two have a chat; I’ll pop across to the other room to see if everything’s all right."},
{character:"Hu Si ",line:" Pleased to meet you; hope you’ll keep an eye on my interests."},
{character:"Fang Dasheng",line:" Er, well—"},
{character:"Hu Si ",line:" Your face looks familiar."},
{character:"Fang Dasheng",line:" Is that so?"},
{character:"Hu Si ",line:" How old are you?"},
{character:"Fang Dasheng",line:" What?"},
{character:"Hu Si ",line:" You’re quite good-looking, no bad at all. You’ll definitely do well here. I say, Doctor Zhang, don’t you think Mr. Fang looks like Huang Yunqiu, that friend of mine?"},
{character:"Georgy Zhang ",line:"Huang Yunqiu?"},
{character:"Hu Si ",line:" The one who takes the ‘staid female’ parts at the Da Wu Tai Opera."},
{character:"Fang Dasheng",line:" And I suppose you’re the soubrette."},
{character:"Hu Si ",line:" Good eyes you’ve got—well, I’m not a professional at it, though I do go in for it. I’m teaching Mrs. Gu and Bailu’s had lessons from me, too."},
{character:"Fang Dasheng",line:" My god!"},
{character:"Hu Si ",line:" Are you hungry, Doctor?"},
{character:"Georgy Zhang ",line:"Me? –No, I’m not hungry!"},
{character:"Mrs. Gu",line:" You? You mean you’re hungry?"},
{character:"Hu Si ",line:" I, um—no, I’m not hungry."},
{character:"Fang Dasheng",line:" Excuse me, I think I’ll go out for a walk."},
{character:"Georgy Zhang ",line:"But, Mr. Fang, you—"},
{character:"Fang Dasheng",line:" You must excuse me."},
{character:"Hu Si ",line:" What a stuck-up so-and-so!"},
{character:"Mrs. Gu",line:" I suppose Bailu’s got bored, so she raked up the cranky creature from who-knows-where to amuse herself with."},
{character:"Georgy Zhang ",line:"It’s weird. I’m not sure now that I have met him before."},
{character:"Hu Si ",line:" Doctor, I can drive now."},
{character:"Mrs. Gu",line:" Right, you haven’t seen him drive yet. He drives awfully fast."},
{character:"Hu Si ",line:" You know what, doctor? I’ve been asked to join a film company to be a jeune premier. So now I’ve started learning all those things—riding, swimming, dancing, dressing in European style."}, 
{character:"Hu Si ",line:"Look, doctor, what do you think of my European outfit? Quite stylish, don’t you think?"},
{character:"Georgy Zhang ",line:"Passable, passable. Though at the very least you should get them made in Hongkong, at the price of no less than two-hundred and seventy."},
{character:"Hu Si ",line:" Heard that? And you wanted me to have a job at the Da Feng Bank for a monthly salary that wouldn’t buy me one Western-style suit!"},
{character:"Mrs. Gu",line:" Don’t be so greedy. Li Shiqing  works hard night and day for only two hundred a month, and that’s because Bailu’s so kind to put in a word with Mr. Pan for him."},
{character:"Hu Si ",line:" That’s because he won’t stand up for himself. Nobody could sell themselves so cheaply as that."},
{character:"Chen Bailu",line:" Come along, the refreshments are ready. Come on in, all of you, and have something to eat. We’re all old friends here today. Look, Georgy’s here, Miss Liu."},
{character:"Georgy Zhang ",line:"Bonjour,Bonjour,Mademoiselle. –Ah, my dear Miss Liu. Don’t get up; let me come and keep you company!"},
{character:"Hu Si ",line:" Get up! I’ve been wanting something to eat since I came in."},
{character:"Mrs. Gu",line:" Couldn’t you say so earlier before? Don’t wait about then!"},
{character:"Hu Si ",line:" Oh, you!"},
{character:"Mrs. Gu",line:" Come on now, Hu Si."},
{character:"Hu Si ",line:" Tcha!"},
{character:"Chen Bailu",line:" But where’s Dasheng? Oh, Mrs. Li, won’t you have something to eat? …Oh, I see, please come in then."},
{character:"Chen Bailu",line:" You want to have a word with Mr. Li?"},
{character:"Mrs. Li  ",line:"Yes, Miss Chen."},
{character:"Chen Bailu",line:" What an affectionate couple you are, can’t bear to be parted after all this time. I really do envy you."},
{character:"Chen Bailu",line:" Fusheng, go and ask Mr. Li to come. Tell him  Mrs. Li  wants a word with him."},
{character:"Wang Fusheng",line:" Very good."},
{character:"Chen Bailu",line:" Oh, and is Mr. Fang out there?"},
{character:"Wang Fusheng",line:" No, I haven’t seen him."},
{character:"Chen Bailu",line:" That’ll be all, then."},
{character:"Chen Bailu",line:" Mrs. Li, will you excuse me a moment, duty calls. Dasheng Dasheng!"},
{character:"Chen Bailu",line:" Is Ms. Fang in the room?"},
{character:"The Shrimp", line:" Mr. Fang?"},
{character:"Chen Bailu",line:" The gentleman who was talking with you just now."},
{character:"The Shrimp", line:"Oh, him. No, he’s not there."},
{character:"Chen Bailu",line:" He’s gone off again. Here, who told you to come out?"},
{character:"The Shrimp", line:"I—I came out on hearing you calling me."},
{character:"Chen Bailu",line:" You already forgotten who came here last night, then?"},
{character:"The Shrimp", line:"All right, Miss."},
{character:"Chen Bailu",line:" Come back. There’s a window in there that opens on to a passage. Close it tightly, you hear?"},
{character:"The Shrimp", line:"Yes, all right."},
{character:"Chen Bailu",line:" Wait a moment! Come here to me. That’s better. Now go back in there and don’t run away! "}, 
{character:"Chen Bailu",line:"Oh, Mr. Li, here you are! Your wife insists on seeing you. You really are a devoted couple."},
{character:"Li Shiqing ",line:" I tell you, Miss Chen, we’re as much as ever we were. My wife would get quite miserable if an hour passes without whispering sweet nothings to me."},
{character:"Chen Bailu",line:" Really! Then I’ll leave you to talk to your hearts’ content. I won’t disturb you then."},
{character:"Li Shiqing ",line:" How did it go? Lost? Won?"},
{character:"Ms. Li ",line:", won’t you let me go home now?"},
{character:"Li Shiqing ",line:" You lost again?"},
{character:"Mrs. Li  ",line:" Yes."},
{character:"Li Shiqing ",line:" You’ve lost the hundred and fifty I gave you?"},
{character:"Mrs. Li  ",line:"Not all of it—though nearly all."},
{character:"Li Shiqing ",line:" But how could you lose all that amount!"},
{character:"Mrs. Li  ",line:"I was nervous, afraid of losing, and that made my play even worse."},
{character:"Li Shiqing ",line:" Nervous? Hasn’t everyone got and equal chance? What’s there to be nervous about? You—you’re like a child in arms!"},
{character:"Mrs. Li  ",line:"I was unwilling to play mahjong, but you would insist that I did. Nor did I want to come here, but you forced me to. "},
{character:"Mrs. Li  ",line:"Still I did as I was told, and came and played for high stakes with all those wealthy people—and when I lose you—"},
{character:"Li Shiqing ",line:" Crying! That’s what you’re fit for! Is this the place for you to start crying?! Making a spectacle of yourself! Now stop crying. I’ve plenty of money here. No more of this nonsense."},
{character:"Mrs. Li  ",line:"I don’t want money."},
{character:"Li Shiqing ",line:" What do you want then?"},
{character:"Mrs. Li  ",line:"I want to go back home."},
{character:"Li Shiqing ",line:" Don’t talk nonsense. Here’s some more. Look, I’ve got a hundred here, look. How about eighty for you to be going on with?"},
{character:"Mrs. Li  ",line:"Where did you get this?"},
{character:"Li Shiqing ",line:" Never you mind."},
{character:"Mrs. Li  ",line:"Where’s your fur coat?"},
{character:"Li Shiqing ",line:" At home, I’m not wearing it this evening."},
{character:"Ms. Li ",line:", what’s that you’ve got here?"},
{character:"Li Shiqing ",line:" It’s a—"},
{character:"Mrs. Li  ",line:"You’ve pawned your fur coat a(gain)—"},
{character:"Li Shiqing ",line:" Don’t shout at the top of your voice like that!"},
{character:"Mrs. Li  ",line:"Oh, dear, Shiqing, what’s the point!"},
{character:"Li Shiqing ",line:" It’s no concern of yours, I told you, it’s none of your business."},
{character:"Ms. Li",line:", I can’t bear it no more. Now will you please let me go home, won’t you? This is no place for us to come for an evening out. No respectable company, not a decent word spoken—"},
{character:"Li Shiqing ",line:" Who says there’s no respectable company? Isn’t Mr. Pan respectable? Look at the way he runs schools and build poor-houses and provides factories—doesn’t that show he’s a good man?"},
{character:"Mrs. Li  ",line:"But haven’t you seen the way he and this Miss Chen—"},
{character:"Li Shiqing ",line:" Of course I have. That’ s because Mr. Pan likes her and because he’s got plenty of cash that he likes spending; what’s all that got to do with respectability?"},
{character:"Mrs. Li  ",line:"Have it your own way, but these are no affair of ours. But isn’t it clear that with this scanty income, we cannot afford to come to this place and keep company with this Miss Chen, with these wealthy people?"},
{character:"Li Shiqing ",line:" How many times have I told you to keep that kind of remark for when you’re at home if you must make them? Don’t come out with them here. Otherwise they might hear you and make you a laughing-stock."},
{character:"Mrs. Li  ",line:"Truly, Shiqing, I’m sure they all laugh at us a bit as it is."},
{character:"Li Shiqing ",line:" What right have they to do that? We play mahjong just as they do, and can pay up as well as any of them! Don’t we spend dollars by the hundred the same they do?"},
{character:"Mrs. Li  ",line:"But what’s the point of that! We’ve got a houseful of children at home! There’s Blossom’s schooling to be paid for, Aroma on the point of engaged, and Little Five poorly again. "}, 
{character:"Mrs. Li  ",line:"Mother hasn’t a decent winter coat to her back. Yet you leave all these things aside, to come here and ruin ourselves playing mahjong with them, paying out a hundred at a time, how—how can I go on playing?"},
{character:"Li Shiqing ",line:" Stop, just stop talking about it."},
{character:"Mrs. Li  ",line:"Isn’t it hard enough for you to be a bank clerk, working yourself to death all day but still can’t make ends meet when you draw your salary at the end of the month, "}, 
{character:"Mrs. Li  ",line:"{without making things worse by going around with your superiors, playing mahjong and keeping company with them? "}, 
{character:"Mrs. Li  ",line:"You come to keep company with them when the kids have no money for schooling; you come to mix with these people when we can’t pay the rent at the end of the month; "}, 
{character:"Mrs. Li  ",line:"still you are sociable all the same when we can’t afford a good doctor—"},
{character:"Li Shiqing ",line:" Stop it! Won’t you stop it! Surely you can see what torture I go through all day? Can’t you see that I’m haunted all the time by the thought of poverty? "}, 
{character:"Li Shiqing",line:"I’m hateful; I never stop cursing my bad luck in not having had a decent father who could have brought me up in more comfortable circumstances, so that I could hold up my head and look after myself better. "}, 
{character:"Li Shiqing ",line:"I’m not so bad as them, the low crowd, you know it. They are no better than me. They’ve no brains, no guts, no heart. What’s so different between us is that they were born with money and social status and I wasn’t. "}, 
{character:"Li Shiqing ",line:"I tell you, there’s no justice or equality in the society we’re in. All those talk of morality and public service are their lies for deluding people. If you work conscientiously, you’ll only die a pauper. All you can do is to burn you boats and fight them in the hope of coming out on top!"},
 {character:"Mrs. Li ",line:", you’re so busy fighting, that you don’t give a thought to our own children. What’s going to become of them?"},
{character:"Li Shiqing ",line:" The children! Humph, were it not for them, you don’t imagine I’d be swallowing my sense of shame, dragging you along to a place like this, do you? "}, 
{character:"Li Shiqing ",line:"What’s Chan Bailu anyway? Something between a dancing-girl, a prostitute, a concubine, but not quite any one of these. Low and cheap!"}, 
{character:"Li Shiqing ",line:"But this old bastard takes a fancy to her, and the old fool’s loaded, so I have to call her ‘Miss’ and agree with everything she says. The way it looks to you, though, I’m going down on my knees to them as if treating my ancestors. "}, 
{character:"Li Shiqing ",line:"Suzhen, you don’t realize how I loathe myself sometimes for giving up my self-esteem and lowering myself to flatter them. Here I am, a man past forty, "}, 
{character:"Li Shiqing ",line:"bowing all the time following these bastards that I have to flatter and be sociable with such low trash as Hu Si. Me, Li Shiqing , a real man, I—"},
{character:"Mrs. Li ",line:", don’t you be upset, don’t get frustrated. I know you. I know how you feel after all you’ve had to put up with."},
{character:"Li Shiqing ",line:" No. I will never get frustrated. Humph, I’m getting up; I’ll be even with them yet. I’m going to be as hard as a stone, no room for sentiments at all. I’m not pitying people or feeling sorry for them any longer. I’ll be selfish, I’ll have my revenge."},
{character:"Mrs. Li  ",line:"Revenge? Who did wrong to you? Whom do you hate?"},
{character:"Li Shiqing ",line:" Everyone. In the twenty years I’ve worked here, look at the shabby way I’ve been treated! But I’ll get somewhere sooner or later, and I’ll let them have it with a vengeance. You’ll see, I’ll be back on my feet again."},
{character:"Pan Yueting",line:" Shiqing! You’re back."},
{character:"Li Shiqing ",line:" I’ve been here some time, sir. I heard you were chatting with someone from the newspaper office so I dare not send someone to invite you over to bother you."},
{character:"Pan Yueting",line:" Were you busy with Mrs. Li?"},
{character:"Li Shiqing ",line:" No, no. You’d better go back in to your game of mahjong."},
{character:"Li Shiqing ",line:" Is there any news from the newspaper office about any special change in the situation."},
{character:"Pan Yueting",line:" It would be no concern of yours if there were; have you bought the government bonds I told you to buy?"},
{character:"Li Shiqing ",line:" Yes, two million altogether, this month’s issue."},
{character:"Pan Yueting",line:" What sort of price did you get them for?"},
{character:"Li Shiqing ",line:" Seven seventy-five."},
{character:"Pan Yueting",line:" And what happened after you’d bought?"},
{character:"Li Shiqing ",line:" I’m afraid it’s not a very favorable reaction. What with rumors flying and money tight and share-prices dropping all the time, and holders of government bonds offloading them; but you, sir, have to go and—"},
{character:"Pan Yueting",line:" I have to go and buy them up."},
{character:"Li Shiqing ",line:" On the expectation of a rise, of course."},
{character:"Pan Yueting",line:" You don’t imagine it’d be in the hope of a fall!"},
{character:"Li Shiqing ",line:" Mr. Pan, it’s not very risky to stock up with bonds in the ordinary way: at a pinch you can always cash them and buy them back later. But now it’s a special "},
{character:"Li Shiqing ",line:"situation, with prices going down and down all the time. If they should settle there’s always hope that they’ll come up again and then you’ll make a packet. But that’s something we’ve no control over."},
{character:"Pan Yueting",line:" How do you know those rumors can be trusted?"},
{character:"Li Shiqing ",line:" Ah, I see, you mean they’re being deliberately put about? By the bear, who want to start covering?"},
{character:"Pan Yueting",line:" Deliberately put about or not, they don’t bother me. I think I should be able to tell a piece of reliable information when I hear it, after all these years I’ve been going in for government bonds."},
{character:"Li Shiqing ",line:" Yet, Mr. Jin’s always got the best inside information, and I heard he’s not buying at all. Also—"},
{character:"Pan Yueting",line:" Mr. Shiqing, it’s always best to mind one’s own business. Do what you’re told to do and keep out of what you’re not told to do at the bank and ask no questions. That’s the rule at the bank."},
{character:"Li Shiqing ",line:" Of course, Mr. Pan. But I was only mentioning it to remind you."},
{character:"Pan Yueting",line:" The bank’s affairs are not open to discussion. Also, I don’t need your reminding. "},
{character:"Li Shiqing ",line:" Very well, sir."},
{character:"Pan Yueting",line:" Have you been to Mr. Jin’s?"},
{character:"Li Shiqing ",line:" Yes. I mentioned the matter of the new building that the bank’s putting up."}, 
{character:"Li Shiqing ",line:"He said he didn’t see how the bank could afford it just now. And then he went on to talk about the difficult state of the market and the way land prices are falling. "}, 
{character:"Li Shiqing ",line:"And he said that as the building’s only been started, it would be advisable to stop work on it at once."},
{character:"Pan Yueting",line:" Haven’t you told him that the contract has been signed and that the earnest-money paid for the building?"},
{character:"Li Shiqing ",line:" Of course, I told him the job had been taken by a foreign contractor, so there was no question of asking for our money bank, which meant that it would be just impossible for the moment to free Mr. Jin’s deposit with us, so could he give us a couple of day’s grace."},
{character:"Pan Yueting",line:" What did he say to that?"},
{character:"Li Shiqing ",line:" He thought for a moment and said ‘We’ll see.’ But I should say from the expression on his face that he’ll most likely change his mind."},
{character:"Pan Yueting",line:" The so-and-so! Not a spark of decency in him!"},
{character:"Li Shiqing ",line:" Oh, and he also asked me whether all the bank’s properties had been mortgaged yet."},
{character:"Pan Yueting",line:" What?! He asked you about that?"},
{character:"Li Shiqing ",line:" Yes. I too thought it a bit of a cheek, though I didn’t answer much to that."},
{character:"Pan Yueting",line:" What did you tell him?"},
{character:"Li Shiqing ",line:" I told him that nothing of that sort had happened. Though I am aware that every inch of the bank’s properties have been mortgaged."},
{character:"Pan Yueting",line:" You—who told you so?"},
{character:"Li Shiqing ",line:" Isn’t it a fact, sir, that a few months ago you’ve mortgaged the bank’s last piece of property, extending from the lane of Changxing to Huangren?"},
{character:"Pan Yueting",line:" Nonsense. Who told you that?"},
{character:"Li Shiqing ",line:" Haven’t you mortgaged it all to the You Hua Company, sir?"},
{character:"Pan Yueting",line:" Oh, em, oh, Shiqing, where did you get this information from? You mean to say that some people know about this?"},
{character:"Li Shiqing ",line:" No, no, set your mind at rest, nobody knows but me. It’s just me that saw the contract you signed."},
{character:"Pan Yueting",line:" You’ve seen the contract? Where?"},
{character:"Li Shiqing ",line:" In your drawer of your desk."},
{character:"Pan Yueting",line:" How dare you—"},
{character:"Li Shiqing ",line:" The fact is, I was rather puzzled by what’s going on in the bank—you, sir, suddenly putting up a large building and buying government bonds at the same time. So, one day, when you were busy seeing a client I took the opportunity to have a look in your drawer. Though I do realize that it was a bit of a liberty to take."},
{character:"Pan Yueting",line:" Shiqing, no, no that’s all right. Not a liberty to take. Good thing to keep an eye on each other. Now won’t you sit down? We can talk this over."},
{character:"Li Shiqing ",line:" Sir, that’s very kind of you."},
{character:"Pan Yueting",line:" No, not at all, sit down, make yourself at home. Now you’ve known about this matter, you understand, of course, that it’s very confidential and not on any account to be divulged to anyone, otherwise it’s going to put the bank in an awkward position."},
{character:"Li Shiqing ",line:" Yes, indeed. I’m aware there have been quite a number of large withdrawals recently."},
{character:"Pan Yueting",line:" Right, then, so we sink or swim together. Let’s help each other and combine forces to keep the bank on its feet. Lately there have been a lot of rumors circulating about the bank, casting doubts on the sufficiency of our reserves."},
{character:"Li Shiqing ",line:" Whereas in actual fact not only are our reserves insufficient, but we’re even short of ready cash. Isn’t that the case with Mr. Jin, for example, wanting to make this withdrawal?"},
{character:"Pan Yueting",line:" But, Shiqing—"},
{character:"Li Shiqing ",line:" All the same, sir, since you’ve announced that the bank’s making money and since your plan for erecting a large new building for the bank, the general rush to withdraw deposits has quietened down a bit."},
{character:"Pan Yueting",line:" You’re not slow, you’ve seen the method in all my madness. So, this building must go up. It doesn’t matter when it’s going to be finished: all that matters is to get it done, to show that the bank’s got plenty of reserves and that it’s on a firm footing."},
{character:"Li Shiqing ",line:" But the bank staff know we’re not making money."},
{character:"Pan Yueting",line:" Hence the vital necessity for keeping quiet about the mortgages and about Mr. Jin’s withdrawal. Just at the moment leaking either of these facts could start a panic, so do be careful."},
{character:"Li Shiqing ",line:" Naturally I shall be careful. All the time I’ve worked under you I’ve been very discreet, and there’s no way I should fail you on this matter."},
{character:"Pan Yueting",line:" I’ve another scheme up my sleeve. If we can make a bit on these government bonds, it’ll tide us over for the present. Once we’re out of the wood I’ll see to it that your loyalty is properly rewarded."},
{character:"Li Shiqing ",line:" You can always rely on me, sir. I—er—I heard recently that your assistant Mr. Zhang is to be transferred?"},
{character:"Pan Yueting",line:" Em, yes, my assistant, yes, he is. Well, if you don’t think that position too low, I’m always prepared to help you."},
{character:"Li Shiqing ",line:" Thanks, sir, thank you. Don’t worry, you can always rely on me to do my utmost for you."},
{character:"Pan Yueting",line:" That’s that. Good—by the way, have you brought the list of redundancies?"},
{character:"Li Shiqing ",line:" Yes."},
{character:"Pan Yueting",line:" About how much will we save by these cuts?"},
{character:"Li Shiqing ",line:" Only about five hundred a month."},
{character:"Pan Yueting",line:" Every little helps. Did you make a deduction from the wages on the building site last pay-day?"},
{character:"Li Shiqing ",line:" Yes, two hundred, I’ve got it with me."},
{character:"Pan Yueting",line:" As much as that? How come?"},
{character:"Li Shiqing ",line:" Not all that much really. I only deducted a mere ten cents for each laborer."},
{character:"Pan Yueting",line:" All right, we’ll deal with it later. Oh, right, I knew there was something else: when you saw Mr. Jin did you mention the matter of that little girl last night?"},
{character:"Li Shiqing ",line:" Yes, I said Miss Chen had taken a great fancy to the kid, so would he spare us any embarrassment."},
{character:"Pan Yueting",line:" What did he say?"},
{character:"Li Shiqing ",line:" He shook his head and said he didn’t know anything about it."},
{character:"Pan Yueting",line:" Curse him. Pretending not to know. Friendship doesn’t mean a thing to him—let him have his way. It’s a kid from the countryside anyway."},
{character:"Li Shiqing ",line:" I’ll do that, sir."},
{character:"Li Shiqing ",line:" Keep on with you hai-ei-hai, just keep on with it, do it all your life! What a batch of stupid bastard. I hate you brats! Why are you forever so honest and stubborn?"},
{character:"Li Shiqing ",line:" Hello, who’s that? Oh, I see, Mr. Zhang from the newspaper office. You want to speak to Mr. Pan? He’s not here…it’s me, Shiqing. You can tell me, it’s all the same. What? Mr. Jin’s buying the same government bonds?"}, 
{character:"Li Shiqing ",line:"How much? Three million! That’s odd… Oh… Oh, I see, no wonder our manager’s been buying them too! …"}, 
{character:"Li Shiqing ",line:"yes, yes, it’s true that government bonds are practically Mr. Jin’s own private property, all up to his manipulation…yes, you’re right, then it looks like a rise after all…right…I’ll go and tell Mr. Pan right away. Good-bye, Mr. Zhang. Good-bye!"},
{character:"Huang Xingsan",line:" Mr… Mr. Li."},
{character:"Li Shiqing ",line:" What—It’s you! "},
{character:"Huang Xingsan",line:" Yes, yes, Mr. Li."},
{character:"Li Shiqing ",line:" You again, but what do you think you’re doing coming around after me here?"},
{character:"Huang Xingsan",line:" Hunger drove me here. I’ve a whole family at home with nothing to eat."},
{character:"Li Shiqing ",line:" You think you’ll get something to eat by coming here? This is a hotel, not a soup-kitchen."},
{character:"Huang Xingsan",line:" Mr., Mr. Li, I’ve pawned everything that can be pawned. I’ve nowhere to turn, otherwise, I’d hardly dare come here again bothering you."},
{character:"Li Shiqing ",line:" Tcha, what am I, you think? A relative of yours? An old friend? Or am I in your debt? Just what are you doing, following me around wherever I go? "},
{character:"Huang Xingsan",line:" You’re quite right, sir, I’ve no such claim on you. But Mr. Li, while I was working at the bank I cost you only thirteen a month."}, 
{character:"Huang Xingsan",line:" I’ve got no relative or friend here, so if you take my job away from me, where am I to get another? By turning me out now, the bank’s as good as taking my life from me."},
{character:"Li Shiqing ",line:" What you’re saying in effect is that the bank should never dismiss anyone. The bank hasn’t undertaken to feed you for the rest of your life, if that’s what you imagine!"},
{character:"Huang Xingsan",line:" No, no, no, I don’t mean that Mr. Li, I—I realize the bank’s treated me well; I’m not being ungrateful. But…you haven’t seen the houseful of lively children at home that I have to find food for every day. "}, 
{character:"Huang Xingsan",line:" Now that the bank’s dismissed me, I’ve no money coming in, we’ve no rice left in the house and they’re all crying out that they’re hungry. And the rent’s six weeks in arrears, so very soon we won’t have a roof over our heads."}, 
{character:"Huang Xingsan",line:" Mr. Li, you haven’t seen what a crowd of children I’ve got; I’ve got no other way to go, and I could only—cry when facing them."},
{character:"Li Shiqing ",line:" Whose fault is it then?"},
{character:"Huang Xingsan",line:" Mr. Li, I’ve done nothing wrong at the bank. I was always off to work at the crack of dawn and I never got home till late at night. I worked from morn till night, Mr. Li—"},
{character:"Li Shiqing ",line:" All right, that’s it. I know you’ve been a conscientious worker, content with your lot, not giving any trouble. "}, 
{character:"Huang Xingsan",line:" But don’t you know there’s a depression, an economic crisis? How many times have I told you, that the bank would be cutting down on staff and salaries? You can’t say I didn’t warn you!"},
{character:"Huang Xingsan",line:" Mr. Li, isn’t the bank putting up large new building at the moment? And they’re still taking on people in the bank, new people."},
{character:"Li Shiqing ",line:" That’s none of your business! It’s all part of the bank’s policy, to improve business. As for dismissing you and taking on new people, I should have thought that after all the years you’ve been in business you’d have learnt that much at least about the way of the world."},
{character:"Huang Xingsan",line:" I—I have, Mr. Li. I am aware I’ve got no one behind to give me a push forward."},
{character:"Li Shiqing ",line:" There you are, then."},
{character:"Huang Xingsan",line:" But I have always thought providence doesn’t let down a man who does his best, so if I work hard I may be able to make up for this deficiency."},
{character:"Li Shiqing ",line:" That’s why the bank’s kept you on for four or five years. Otherwise, you don’t think you’d stay on this long."},
{character:"Huang Xingsan",line:" But, Mr. Li, I beg of you, help me just this once. Won’t you please have a word with Mr. Pan, and ask him to take me back? "}, 
{character:"Huang Xingsan",line:" I’d do anything, willingly, even if it means extra work, extra tiredness, even if I have to work myself to death."},
{character:"Li Shiqing ",line:" You’re a pest. You don’t imagine the manager’s going to bother with your troubles? There’s only one thing wrong with people like you: always attaching too much importance to yourselves. In other words, you people are simply selfish. How do you imagine a busy man like Mr. Pan’s going to find time for your petty problems? But, it’s strange that for all these years you’ve been working at the bank, you’ve not at least a small amount of savings?"},
{character:"Huang Xingsan",line:" Savings? What, on thirteen a month with a large family to feed? Savings?"},
{character:"Li Shiqing ",line:" I was not talking about your salary. There can be nothing extra made out of your salary. But surely—you’ve made yourself something on the side, in other ways?"},
{character:"Huang Xingsan",line:" No, I always kept my conscience clear, Mr. Li."},
{character:"Li Shiqing ",line:" I mean—surely you made something for yourself out of buying stationery?"},
{character:"Huang Xingsan",line:" Never, my conscience would never allow it. You can ask Mr. Liu the chief clerk."},
{character:"Li Shiqing ",line:" Humph! You must be a fool if you’re as particular as that about your conscience! No wonder you’re in such a pitiful state now. All right, get out now. "},
{character:"Huang Xingsan",line:" But, Mr. Li—"},
{character:"Li Shiqing ",line:" We’ll reconsider the matter if anything turns up. At the moment there’s nothing I can do for you. Now go."},
{character:"Huang Xingsan",line:" But, Mr. Li, you can’t—"},
{character:"Li Shiqing ",line:" And, tell you what, if you keep on following me like a dog, trotting around everywhere I go, you’ll find I won’t play nice next time."},
{character:"Huang Xingsan",line:" Then, Mr. Li, there’s no hope at all?"},
{character:"Li Shiqing ",line:" Get moving! There’ll be a whole lot of ladies coming in here in a minute; if they find you coming to see me here, just consider how awkward it would be!"},
{character:"Huang Xingsan",line:" All right, then. Mr. Li, I really must apologize for treating you like this. Coming and bothering you all the time. I’ll go now."},
{character:"Li Shiqing ",line:" You’re really a pest. Just go on."},
{character:"Huang Xingsan",line:" But, where can I go? Just please tell me where can I go? My home’s broken up now, I’ll swallow my pride and tell you: "}, 
{character:"Huang Xingsan",line:"my wife’s left me. We had nothing to eat and she couldn’t bear our miserable existence any longer, so she ran off with someone else."}, 
{character:"Huang Xingsan",line:"There are three children at home, waiting for me to take them home something to eat. Right now I’ve only twenty cents in my pocket and I’m also ill, all day long I’m coughing! Mr. Li, tell me where can I go? Just, where can I go?"},
{character:"Li Shiqing ",line:" Go where you like. I’m telling you: it’s not that I don’t want to help you out with some money, but I can’t make a precedent of your case."},
{character:"Huang Xingsan",line:" I didn’t beg you for money, all I’m asking you to do is to be so kind as to give me a job. I must live, for my children’s sake!"},
{character:"Li Shiqing ",line:" Actually there are plenty of jobs out there if only you’re willing to take them."},
{character:"Huang Xingsan",line:" You mean that?"},
{character:"Li Shiqing ",line:" First, you can go rickshaw-pulling."},
{character:"Huang Xingsan",line:" I—I could never manage it. You know I’m ill. The doctor says I can no longer—depend on the lung on this side."},
{character:"Li Shiqing ",line:" I see, in that case you can always go out to the street and start beg—"},
{character:"Huang Xingsan",line:" Mr. Li, I have had an education, you know. I just couldn’t—"},
{character:"Li Shiqing ",line:" You just couldn’t bring yourself to accost people, is that it? Well there’s still another way left open to you, "}, 
{character:"Li Shiqing ",line:"an extremely easy way that will give you what you want without any fuss: you can go into others’ houses and—yes, that’s right, you’ve got it."},
{character:"Huang Xingsan",line:" What, you mean—you mean I can turn to—"},
{character:"Li Shiqing ",line:" Say it out loud! What are you afraid of? ‘To steal!’ ‘To steal!’ Why not, after all? When the rich can grab money by the fistful from others’ pockets, it surely doesn’t require very much courage to steal!"},
{character:"Huang Xingsan",line:" Mr. Li, I have been driven to thinking of it."},
{character:"Li Shiqing ",line:" Oh? You’ve been driven to think of theft?"},
{character:"Huang Xingsan",line:" But I’m afraid to, I’m afraid, I could never bring myself to it."},
{character:"Li Shiqing ",line:" What do you expect me to do when you have not the guts to steal?"}, 
{character:"Li Shiqing ",line:"You’ve got no influential relatives nor dependable friends, nor have you any outstanding skills. So there you are: I told you to beg, but your pride gets in the way; told you to pull a riskshaw, but you haven’t the strength; "}, 
{character:"Li Shiqing",line:"told you to steal, but you’re too afraid to do. You keep belly-aching about conscience and altruism, dreaming of depending on honesty and humility only to raise your wife and family; "}, 
{character:"Li Shiqing",line:"why, if you can’t even provide for a wife, you’re simply a poor useless thing, unfit to have a family! I’m now telling you, this world is not meant for people like you! "}, 
{character:"Li Shiqing",line:"See that high-rise building out there? That’s Xinhua Department Store, thirteen-story high. I think that might be the best way out for you."},
{character:"Huang Xingsan",line:" But how, Mr. Li?"},
{character:"Li Shiqing ",line:" How? Let me tell you. You climb up, story after story, and when you get to the very top you get over the railings and stand on the edge. Then all you have to do is to take one step forward, just one more into space. It may be rather frightening for that moment, but it will only take one second to free you from your misery, with no more worries about finding food and clothing—"},
{character:"Huang Xingsan",line:" Mr. Li, are you talking about my committing— No! No！I mustn’t die, Mr. Li, I must stay alive!"}, 
{character:"Huang Xingsan",line:"For my children’s sake, for my children who’ve lost their mother, I must live for them! My Aurora, my Cloudy, my—Oh, yes, I had thought of it, but Mr. Li, you must help me, just this once, help me to stay alive! "}, 
{character:"Huang Xingsan",line:"I mustn’t die no matter how hard it becomes to live, I must stay alive at all costs!"},
{character:"Li Shiqing ",line:" Let go of me. Someone’s coming in, so behave yourself."},
{character:"Pan Yueting",line:" Ah?"},
{character:"Huang Xingsan",line:" Sir!"},
{character:"Pan Yueting",line:" Shiqing, who’s this? What’s he doing here?"},
{character:"Huang Xingsan",line:" Sir, I’m Huang, I’m clerk at the Da Feng Bank."},
{character:"Li Shiqing ",line:" He’s one of those who’ve just been dismissed."},
{character:"Pan Yueting",line:" What do you mean by coming here? Who let him in?"},
{character:"Li Shiqing ",line:" No idea how he found his way in."},
{character:"Huang Xingsan",line:" Sir, would you please be good to me. If you have to dismiss someone don’t let it be me. I’ve got three kids, I must have a job. Sir, I’m going down on my knees to you, you must let me go on living."},
{character:"Pan Yueting",line:" I’ve never heard of such a thing! How dare this guy come here asking me for a job! Get out!"},
{character:"Huang Xingsan",line:" But, sir—"},
{character:"Li Shiqing ",line:" Get up! Get up! Go on! Get out! Go! If you must make a nuisance of yourself I’ll get somebody in to kick you out."},
{character:"Pan Yueting",line:" Out, get out! Quickly! I’ve never heard of such a thing!"},
{character:"Huang Xingsan",line:" All right, I’ll get up, I’ll get up as you wish! You needn’t hit me! So you’re not going to let me stay alive! You! And you! {Neither of you will let me go on living. Oh, it’s not fair. You’re a couple of heartless monsters!"}, 
{character:"Huang Xingsan",line:" Only thirteen a month you paid me, though with all those deductions you made all I got every month was only ten and twenty-five. And for this miserable ten and twenty-five I spent all day writing, bending my back and neck down onto the desk writing for you;"}, 
{character:"Huang Xingsan",line:" I had to write on without a chance to look up or draw a breath; I wrote from morn till night; with a cold sweat on my back and the words blurring before my eyes I had to keep writing, on and on; "}, 
{character:"Huang Xingsan",line:" through wind and rain I rushed to the bank to write for you! Five years! Mr. Pan! Take a look at me, see what’s left of me after five years of that!"}, 
{character:"Huang Xingsan",line:" A walking skeleton, a man at death’s door! I tell you both, my left lung has already gone, yes, rotten away as the doctor says! "}, 
{character:"Huang Xingsan",line:" I’m telling you, I’m a man at death’s door, I’m going down on my knees to you just for the sake of my poor children, just to ask you to give me a chance to write on and on for you, to earn a living from you, to exchange my worthless life for a few more ten and twenty-fives. "}, 
{character:"Huang Xingsan",line:" But you won’t let me! You won’t! You want to make money for yourselves, you must cut down your staff, you must dismiss me!"}, 
{character:"Huang Xingsan",line:" But what do you want this ten and twenty-five for? "}, 
{character:"Huang Xingsan",line:" I’m not taking away your money for nothing, I’m exchanging my life for it! And I won’t even take a few more ten twenty-fives from you before I die."}, 
{character:"Huang Xingsan",line:" There’s not a spark of decency in either of you, the way you are treating me—you thieves, robbers, you devils! "}, 
{character:"Huang Xingsan",line:" Even beasts of the field have got more conscience than you do—"},
{character:"Pan Yueting",line:" You’re mad, you scoundrel! Get out of my sight this minute!"},
{character:"Huang Xingsan",line:" Now I’m not afraid of you! Not any longer! It’s not fair, I’m determined to kill—"},
{character:"Pan Yueting",line:" What!"},
{character:"Li Shiqing ",line:" He means he’s going to kill himself, sir.—A man like that wouldn’t hurt a fly."},
{character:"Pan Yueting",line:" It doesn’t matter now. He’s just passed out. Fusheng! Fusheng!"},
{character:"Pan Yueting",line:" Get him out of here. Put him in another room and tell Mr. Jin’s men to massage him till he comes round, then give him three bucks and tell him to clear out!"},
{character:"Wang Fusheng",line:" Yes, sir!"},
{character:"Li Shiqing ",line:" Mr. Zhang rang through."},
{character:"Pan Yueting",line:" What did he say?"},
{character:"Li Shiqing ",line:" Mr. Jin’s bought three million of the same bonds as you."},
{character:"Pan Yueting",line:" I knew it! Then, that means he’s expecting a rise."},
{character:"Li Shiqing ",line:" So long as the information’s reliable, that Mr. Jin is buying, then of course he’s expecting a rise."},
{character:"Pan Yueting",line:" It must not be unreliable, it must be right."},
{character:"Georgy Zhang ",line:"–So I maintain that it’s hard to live in China, nowhere where you can live in comfort. "}, 
{character:"Georgy Zhang",line:" You’ve only to look at my Jacky—the hunting dog I bought back from America with me—even finding the beef for him to eat is a great problem for me every day. "}, 
{character:"Georgy Zhang",line:" Dirty, unclean nor nourishing, and fifty cents a pound, why he just can’t eat it. You see, I put four pounds of raw beef in front of him every day, only to see him sniffing at it and then going off with his tail between his legs without even looking at it. "}, 
{character:"Georgy Zhang",line:" Just think how people suffer in China when animals are feeling the pinch here! And as for people like us, well!"},
{character:"Chen Bailu",line:" Listen, what’s Dasheng shouting about?"},
{character:"Fang Dasheng",line:" The Shrimp! Zhujun, have you seen the Shrimp?"},
{character:"Chen Bailu",line:" Why, isn’t she in the room?"},
{character:"Fang Dasheng",line:" In the room? Shrimp! Shrimp!"},
{character:"Mrs. Gu",line:" What’s all this about?"},
{character:"Fang Dasheng",line:" No, she’s not in there, she’s gone. As I was coming up the stairs just now I saw her go down in the lift with two or three men. "}, 
{character:"Fang Dasheng",line:"I only caught a glimpse of her and she disappeared. I could hardly believe my eyes but when I come and look I find she has been taken away after all. Good-bye! I’m going to look for her."},
{character:"Chen Bailu",line:" Yueting, see what happens when I ask you to do something for me! Wait for me, Dasheng! I’m coming with you!"},
{character:"Pan Yueting",line:" Bailu!"},
{character:"Georgy Zhang ",line:"Look! Just another—"},
{character:"Hu Si and Mrs. Gu ",line:"Mad one!"},
  ];

const nextSlide = useCallback(() => {
    setCurrentSlide((prevSlide) => (prevSlide + 1) % slides.length);
  }, [slides.length]);

  // Function to go to the previous slide
const prevSlide = useCallback(() => {
    setCurrentSlide((prevSlide) => (prevSlide - 1 + slides.length) % slides.length);
  }, [slides.length]);

  useEffect(() => {
    const handleKeyDown = (event) => {
      if (event.key === 'ArrowRight') {
        nextSlide(); // Right arrow key pressed
      } else if (event.key === 'ArrowLeft') {
        prevSlide(); // Left arrow key pressed
      }
    };

    window.addEventListener('keydown', handleKeyDown); // Add event listener for keydown

    return () => {
      window.removeEventListener('keydown', handleKeyDown); // Clean up event listener on unmount
    };
  }, [nextSlide, prevSlide]);

  return (
    <div className="relative">
      <Slide {...slides[currentSlide]} />
      <button
        className="absolute top-3/4 left-4 bg-white text-black p-2 rounded"
        onClick={prevSlide}
      >
        Previous
      </button>

      <button
        className="absolute top-3/4 right-4 bg-white text-black p-2 rounded"
        onClick={nextSlide}
      >
        Next
      </button>
      <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 text-white">
        {currentSlide + 1} / {slides.length}
      </div>
    </div>
  );
};

export default Slideshow2;